import type { Stat } from '../core/model';
import type { Tag } from '../core/tags';
import type { CardDef, Recover } from './defs';
import type { Fx } from './fx';

/**
 * 共通語彙《ベーシック》。誰でも使える 67 枚。単体では地味だが、規則の
 * 隙間に差し込む部品になる（真似る・書き留める・誓う・燃やす）。
 */
function b(
  no: number,
  id: string,
  name: string,
  tags: Tag[],
  stats: Stat[],
  uses: number,
  ready: Fx[],
  spentName: string,
  spent: Fx[],
  recover: Recover[],
  flavor: string,
  rarity: CardDef['rarity'] = 'common',
  extra: Partial<CardDef> = {},
): CardDef {
  return {
    ...extra,
    id,
    layer: 'basic',
    no,
    name,
    tags,
    stats,
    uses,
    rarity,
    ready,
    spentName,
    spent,
    recover: { on: recover },
    since: '1.2.0',
    flavor,
  };
}

export const BASICS: readonly CardDef[] = [
  b(
    101,
    'look',
    '見る',
    ['gaze'],
    ['INT'],
    4,
    [['see']],
    '目を凝らす',
    [['see'], ['clue', 1, true], ['cost', 0, 1]],
    ['uncover'],
    'まず、見る。',
  ),
  b(
    102,
    'listen',
    '聞く',
    ['person', 'trust'],
    ['WIL'],
    4,
    [
      ['trust', 1],
      ['if', ['trustHalf'], [['clue', 1]]],
    ],
    '聞き流す',
    [
      ['trust', 1],
      ['cost', 0, 1],
    ],
    ['trusted'],
    '相手が話し終えるまで待つ。',
  ),
  b(
    103,
    'hush',
    '黙る',
    ['private', 'time'],
    ['WIL'],
    4,
    [
      ['calm', 3],
      ['host', -1],
    ],
    '押し黙る',
    [
      ['calm', 4],
      ['trust', -1],
    ],
    ['quiet'],
    '言わないことも、言葉のうち。',
  ),
  b(
    104,
    'push',
    '押し返す',
    ['body'],
    ['ATK'],
    4,
    [['hit', { n: 3, s: 'ATK' }]],
    '振り払う',
    [
      ['hit', { n: 5, s: 'ATK' }],
      ['cost', 1],
    ],
    ['win'],
    '手のひらで、相手の胸を。',
  ),
  b(
    105,
    'brace',
    '構え直す',
    ['body', 'time'],
    ['DEF'],
    4,
    [['guard', { n: 4, s: 'DEF' }]],
    '踏みとどまる',
    [
      ['guard', { n: 6, s: 'DEF' }],
      ['cost', 0, 1],
    ],
    ['win'],
    '足の位置を変える。',
  ),
  b(
    106,
    'fib',
    '嘘をつく',
    ['private'],
    ['INT'],
    3,
    [['lie', 2]],
    '言い張る',
    [['lie', 3, 10]],
    ['lieKept'],
    '小さな嘘から始める。',
  ),
  b(
    107,
    'run',
    '走る',
    ['place', 'body'],
    ['AGI'],
    2,
    [
      ['guard', 2],
      ['check', 'AGI', 40, [['leave']]],
    ],
    '逃げ出す',
    [['leave', true]],
    [],
    'どこへ、とは決めずに。',
  ),
  b(
    108,
    'pinch',
    '盗む',
    ['private', 'body'],
    ['AGI'],
    3,
    [
      [
        'check',
        'AGI',
        30,
        [
          ['coins', 6],
          ['clue', 1],
        ],
        [['host', 2]],
      ],
    ],
    'ひったくる',
    [
      ['coins', 8],
      ['host', 4],
    ],
    ['left'],
    'ポケットの中身は、持ち主の記憶でもある。',
  ),
  b(
    109,
    'pay',
    '払う',
    ['public', 'trust'],
    ['INT'],
    3,
    [
      ['coins', -6],
      ['trust', 2],
    ],
    '札束を見せる',
    [
      ['coins', -12],
      ['trust', 3],
    ],
    ['trusted'],
    '値段のつく話は早い。',
  ),
  b(
    110,
    'note',
    '書き留める',
    ['public', 'memory'],
    ['INT'],
    3,
    [['note'], ['see']],
    '走り書き',
    [['note'], ['cost', 0, 1]],
    ['quiet'],
    '次の一手のために、いまを書いておく。',
    'uncommon',
  ),
  b(
    111,
    'measure',
    '測る',
    ['place', 'gaze'],
    ['INT'],
    3,
    [['see'], ['expose', 1]],
    '目測',
    [
      ['expose', 2],
      ['cost', 0, 1],
    ],
    ['newPlace'],
    '距離と角度。',
  ),
  b(
    112,
    'pray',
    '祈る',
    ['trust', 'time'],
    ['WIL'],
    3,
    [['heal', 0, 3]],
    'すがる',
    [
      ['heal', 0, 2],
      ['cost', 1],
    ],
    ['quiet'],
    '誰に、とは決めていない。',
  ),
  b(
    113,
    'shout',
    '怒鳴る',
    ['body', 'public'],
    ['ATK', 'WIL'],
    3,
    [
      ['break', { n: 3, s: 'ATK', m: 0.5 }],
      ['host', 2],
    ],
    '喚く',
    [
      ['break', { n: 5, s: 'ATK', m: 0.5 }],
      ['host', 3],
      ['trust', -2],
    ],
    ['broken'],
    '声を大きくすれば、相手は小さくなる。たいていは。',
  ),
  b(
    114,
    'wait',
    '待つ',
    ['time'],
    ['WIL'],
    4,
    [
      ['cut', 3],
      ['calm', 2],
    ],
    '待ちくたびれる',
    [
      ['cut', 2],
      ['host', 1],
    ],
    ['quiet'],
    '相手が先に動くのを。',
  ),
  b(
    115,
    'recall',
    '思い出す',
    ['memory'],
    ['WIL'],
    2,
    [['heal', 0, { n: 1, per: 'memory' }]],
    '反芻',
    [
      ['heal', 0, 2],
      ['cost', 1],
    ],
    ['newPlace'],
    '同じ夜を、何度でも。',
  ),
  b(
    116,
    'call',
    '呼ぶ',
    ['person', 'night'],
    ['WIL'],
    3,
    [
      ['trust', 1],
      ['guard', 3],
    ],
    '叫ぶ',
    [
      ['guard', 4],
      ['host', 1],
    ],
    ['trusted'],
    '呼べば、誰かが来る。来なくても。',
  ),
  b(
    117,
    'hide',
    '隠れる',
    ['place', 'night'],
    ['AGI'],
    3,
    [['guard', 6]],
    '息を殺す',
    [['cost', 0, 1], ['leave']],
    ['left'],
    '暗がりは、いつも一歩先にある。',
  ),
  b(
    118,
    'vow',
    '誓う',
    ['trust', 'institution'],
    ['WIL'],
    2,
    [['vow'], ['trust', 2]],
    '重ねて誓う',
    [['vow'], ['trust', 3], ['cost', 0, 1]],
    ['trusted'],
    '本当の約束。だから、破ると重い。',
    'uncommon',
  ),
  b(
    119,
    'burn',
    '燃やす',
    ['tech', 'memory'],
    ['WIL'],
    2,
    [
      ['break', 4],
      ['cost', 0, 1],
    ],
    '焼き捨てる',
    [['burnBad'], ['cost', 3]],
    ['broken'],
    '残しておきたくないものもある。',
    'uncommon',
  ),
  b(
    120,
    'mimic',
    '真似る',
    ['person', 'gaze'],
    ['AGI'],
    3,
    [['mimic', 0.7]],
    'なりきる',
    [
      ['mimic', 1],
      ['cost', 0, 2],
    ],
    ['uncover'],
    '同じ手を、もう一度。今度は自分の手で。',
    'uncommon',
  ),
  // ─── 121〜160：言葉・からだ・道具・時間。部品として、規則の隙間に差す ───
  b(
    121,
    'ask',
    '尋ねる',
    ['person', 'public'],
    ['INT'],
    4,
    [['if', ['trustHalf'], [['clue', 1]], [['see']]]],
    '問い詰める',
    [
      ['clue', 1],
      ['host', 2],
    ],
    ['uncover'],
    '答えより、答えるまでの間を聞く。',
  ),
  b(
    122,
    'nod',
    '頷く',
    ['trust', 'person'],
    ['WIL'],
    4,
    [
      ['trust', 1],
      ['calm', 2],
    ],
    '相槌',
    [
      ['trust', 1],
      ['cost', 0, 1],
    ],
    ['trusted'],
    '聞いている、と伝えるだけでいい。',
  ),
  b(
    123,
    'stare',
    '睨む',
    ['gaze', 'body'],
    ['ATK'],
    3,
    [
      ['break', { n: 2, s: 'ATK', m: 0.5 }],
      ['host', 1],
    ],
    '睨みつける',
    [
      ['break', 4],
      ['host', 3],
    ],
    ['broken'],
    '先に目を逸らしたほうが負ける。',
  ),
  b(
    124,
    'lean',
    '寄りかかる',
    ['place', 'body'],
    ['DEF'],
    4,
    [
      ['guard', { n: 3, s: 'DEF' }],
      ['calm', 1],
    ],
    '座り込む',
    [
      ['guard', 6],
      ['cost', 0, 1],
    ],
    ['quiet'],
    '壁は、たいてい味方だ。',
  ),
  b(
    125,
    'smoke',
    '煙草を吸う',
    ['time', 'body', 'night'],
    ['WIL'],
    3,
    [
      ['calm', 3],
      ['heal', 0, 1],
    ],
    '吸い殻を噛む',
    [
      ['calm', 2],
      ['cost', 1],
    ],
    ['quiet'],
    '火をつけるあいだは、誰も急かさない。',
  ),
  b(
    126,
    'drink',
    '一杯やる',
    ['body', 'night', 'public'],
    ['VIT'],
    3,
    [
      ['heal', 2],
      ['if', ['foeTag', 'person'], [['trust', 1]]],
    ],
    '飲みすぎる',
    [
      ['heal', 3],
      ['host', 1],
      ['cost', 0, 2],
    ],
    ['win'],
    '同じ瓶から注げば、話は早い。',
  ),
  b(
    127,
    'joke',
    '冗談を言う',
    ['person', 'public'],
    ['WIL'],
    3,
    [
      ['host', -1],
      ['check', 'WIL', 40, [['trust', 2]], [['trust', 1]]],
    ],
    '滑る',
    [['host', 1]],
    ['trusted'],
    '笑わせるのは、斬るより難しい。',
  ),
  b(
    128,
    'flatter',
    'おだてる',
    ['person', 'private'],
    ['INT'],
    3,
    [
      ['trust', 2],
      ['if', ['foeTag', 'institution'], [['host', 1]]],
    ],
    '媚びる',
    [
      ['trust', 2],
      ['cost', 0, 2],
    ],
    ['trusted'],
    '役人だけは、褒められると疑う。',
  ),
  b(
    129,
    'threaten',
    '脅す',
    ['body', 'private'],
    ['ATK'],
    3,
    [
      ['break', { n: 3, s: 'ATK', m: 0.5 }],
      ['host', 2],
      ['if', ['hostile', 7], [['break', 3]]],
    ],
    '凄む',
    [
      ['break', 5],
      ['host', 4],
    ],
    ['broken'],
    '怒っている相手ほど、脅しはよく効く。',
  ),
  b(
    130,
    'bribe',
    '握らせる',
    ['private', 'institution'],
    ['INT'],
    2,
    [
      ['coins', -10],
      ['clue', 1],
    ],
    '有り金を',
    [
      ['coins', -20],
      ['clue', 2],
    ],
    ['uncover'],
    '紙幣は、いちばん口の軽い紙だ。',
  ),
  b(
    131,
    'search',
    '探る',
    ['private', 'gaze'],
    ['INT'],
    3,
    [['check', 'INT', 45, [['clue', 1]], [['host', 1]]]],
    '漁る',
    [
      ['clue', 1],
      ['host', 2],
    ],
    ['uncover'],
    '引き出しの二段目。',
  ),
  b(
    132,
    'sketch',
    '見取り図',
    ['place', 'public'],
    ['INT'],
    3,
    [
      ['expose', 1],
      ['guard', 2],
    ],
    '殴り書きの図',
    [['expose', 1]],
    ['newPlace'],
    '出口の数を、先に数える。',
  ),
  b(
    133,
    'clock',
    '時計を見る',
    ['time'],
    ['INT'],
    4,
    [
      ['cut', 2],
      ['if', ['hour', 4], [['cut', 2]]],
    ],
    '秒針を数える',
    [
      ['cut', 3],
      ['cost', 0, 1],
    ],
    ['quiet'],
    '夜が深いほど、時計は役に立つ。',
  ),
  b(
    134,
    'stall',
    '時間を稼ぐ',
    ['time', 'public'],
    ['WIL'],
    3,
    [
      ['cut', 3],
      ['guard', 2],
    ],
    '引き延ばす',
    [
      ['cut', 4],
      ['host', 1],
    ],
    ['left'],
    '何も決めないことを、決める。',
  ),
  b(
    135,
    'dodge',
    'かわす',
    ['body'],
    ['AGI'],
    4,
    [['guard', { n: 2, s: 'AGI' }]],
    '転がる',
    [
      ['guard', { n: 4, s: 'AGI' }],
      ['cost', 1],
    ],
    ['win'],
    '当たらなければ、傷にもならない。',
  ),
  b(
    136,
    'trip',
    '足を払う',
    ['body', 'place'],
    ['AGI'],
    3,
    [['stun'], ['hit', 2]],
    '引き倒す',
    [['stun'], ['hit', 3], ['host', 3]],
    ['win'],
    '床は、誰にでも等しく硬い。',
  ),
  b(
    137,
    'grab',
    '掴む',
    ['body'],
    ['ATK'],
    4,
    [
      ['hit', { n: 2, s: 'ATK' }],
      ['cut', 1],
    ],
    '締め上げる',
    [
      ['hit', { n: 4, s: 'ATK' }],
      ['host', 2],
    ],
    ['win'],
    '襟元を。',
  ),
  b(
    138,
    'light',
    '明かりをつける',
    ['place', 'night', 'gaze'],
    ['INT'],
    3,
    [['see'], ['expose', 1], ['if', ['night'], [['clue', 1]]]],
    '照らし出す',
    [['see'], ['clue', 1], ['host', 2]],
    ['uncover'],
    '見つけたら、明かりをつけて。',
    'uncommon',
  ),
  b(
    139,
    'photo',
    '写真を撮る',
    ['gaze', 'tech', 'memory'],
    ['INT'],
    2,
    [['clue', 1], ['note']],
    'フラッシュ',
    [['stun'], ['host', 2]],
    ['uncover'],
    '残すことは、奪うことに似ている。',
  ),
  b(
    140,
    'record',
    '録音する',
    ['tech', 'private'],
    ['INT'],
    3,
    [['note'], ['see']],
    '盗聴',
    [
      ['clue', 1],
      ['cost', 0, 1],
    ],
    ['quiet'],
    'テープは、言い直しを許さない。',
  ),
  b(
    141,
    'phone',
    '電話をかける',
    ['tech', 'person', 'night'],
    ['WIL'],
    2,
    [
      ['refill', 'person', 1],
      ['guard', 2],
    ],
    '長電話',
    [
      ['heal', 0, 3],
      ['cost', 1],
    ],
    ['newPlace'],
    '真夜中に出てくれる番号が、ひとつだけある。',
  ),
  b(
    142,
    'file',
    '書類を出す',
    ['institution', 'public'],
    ['INT'],
    3,
    [['if', ['foeTag', 'institution'], [['break', 6]], [['break', 2]]]],
    '書類の山',
    [
      ['break', 4],
      ['cost', 0, 1],
    ],
    ['broken'],
    '判子のある紙には、判子のある紙で。',
  ),
  b(
    143,
    'badge',
    '身分を偽る',
    ['institution', 'private'],
    ['INT'],
    2,
    [['lie', 3, 0, 'authority']],
    '偽の身分証',
    [['lie', 4, -10, 'authority']],
    ['lieKept'],
    '制服の半分は、態度でできている。',
  ),
  b(
    144,
    'rule',
    '規則を盾にする',
    ['institution'],
    ['WIL'],
    3,
    [
      ['guard', 4],
      ['calm', 2],
      ['host', 1],
    ],
    '規則を読み上げる',
    [
      ['guard', 5],
      ['break', 2],
    ],
    ['win'],
    '第何条かは、言わなくていい。',
  ),
  b(
    145,
    'testify',
    '証言する',
    ['public', 'trust', 'memory'],
    ['WIL'],
    2,
    [
      ['trust', 2],
      ['if', ['shown', 1], [['clue', 1]]],
    ],
    '偽証',
    [['lie', 3, 0, 'knows']],
    ['trusted'],
    '見たことを、見たとおりに。それがいちばん難しい。',
  ),
  b(
    146,
    'confess',
    '打ち明ける',
    ['private', 'trust'],
    ['WIL'],
    2,
    [
      ['trust', 3],
      ['cost', 0, 2],
    ],
    '洗いざらい',
    [
      ['trust', 4],
      ['host', -2],
      ['cost', 0, 3],
    ],
    ['trusted'],
    '秘密は、手放した分だけ軽くなる。',
  ),
  b(
    147,
    'forget',
    '忘れる',
    ['memory', 'time'],
    ['WIL'],
    2,
    [
      ['heal', 0, 3],
      ['calm', 2],
    ],
    '忘れたふり',
    [['calm', 3]],
    ['quiet'],
    '覚えていないことにする。今夜だけ。',
  ),
  b(
    148,
    'keepsake',
    '形見を握る',
    ['memory', 'private'],
    ['WIL'],
    3,
    [['calm', { n: 1, per: 'memory' }]],
    '形見を見せる',
    [
      ['trust', 2],
      ['cost', 0, 1],
    ],
    ['newPlace'],
    'ポケットの中で、角が丸くなった。',
  ),
  b(
    149,
    'hum',
    '口ずさむ',
    ['time', 'memory'],
    ['WIL'],
    4,
    [
      ['calm', 2],
      ['heal', 0, 1],
    ],
    '歌う',
    [
      ['trust', 1],
      ['host', 1],
    ],
    ['quiet'],
    '題名を思い出せない歌。',
  ),
  b(
    150,
    'sweep',
    '掃除する',
    ['place', 'time'],
    ['DEF'],
    3,
    [
      ['guard', 2],
      ['refill', 'place', 1],
    ],
    '片付けない',
    [['guard', 3]],
    ['newPlace'],
    '床が見えると、考えも見える。',
  ),
  b(
    151,
    'knock',
    '戸を叩く',
    ['place', 'public'],
    ['WIL'],
    3,
    [['trust', 1], ['see']],
    '叩き続ける',
    [
      ['break', 3],
      ['host', 2],
    ],
    ['trusted'],
    '三回。間をあけて、もう二回。',
  ),
  b(
    152,
    'step',
    '一歩下がる',
    ['body', 'place'],
    ['AGI'],
    4,
    [
      ['guard', 3],
      ['cut', 1],
    ],
    '後ずさる',
    [
      ['guard', 2],
      ['check', 'AGI', 50, [['leave']]],
    ],
    ['left'],
    '間合いは、退いて作る。',
  ),
  b(
    153,
    'feint',
    '見せかける',
    ['body', 'private'],
    ['AGI'],
    3,
    [
      ['lie', 1],
      ['hit', { n: 2, s: 'AGI' }],
    ],
    '不意打ち',
    [
      ['hit', { n: 5, s: 'AGI' }],
      ['host', 3],
    ],
    ['win'],
    '手は出さない、と言いながら。',
    'uncommon',
  ),
  b(
    154,
    'count',
    '数える',
    ['gaze', 'institution'],
    ['INT'],
    4,
    [
      ['expose', 1],
      ['if', ['shown', 2], [['break', 3]]],
    ],
    '数え直す',
    [
      ['expose', 2],
      ['cost', 0, 1],
    ],
    ['uncover'],
    '合わない数は、嘘の居場所だ。',
  ),
  b(
    155,
    'compare',
    '照らし合わせる',
    ['memory', 'gaze', 'public'],
    ['INT'],
    2,
    [['if', ['shown', 1], [['clue', 1]], [['see']]]],
    '突き合わせる',
    [
      ['clue', 1],
      ['host', 2],
    ],
    ['uncover'],
    '昨日の言葉と、今日の言葉。',
  ),
  b(
    156,
    'sleep',
    '目を閉じる',
    ['body', 'time', 'night'],
    ['VIT'],
    2,
    [['heal', 3, 1]],
    '寝落ち',
    [
      ['heal', 4, 2],
      ['host', 2],
    ],
    ['quiet'],
    '五分だけ。',
  ),
  b(
    157,
    'walk',
    '歩き回る',
    ['place', 'body'],
    ['AGI'],
    3,
    [
      ['guard', 2],
      ['expose', 1],
    ],
    'さまよう',
    [
      ['refill', 'place', 1],
      ['cost', 1],
    ],
    ['newPlace'],
    '同じ角を、三度曲がる。',
  ),
  b(
    158,
    'trade',
    '物々交換',
    ['public', 'private'],
    ['INT'],
    3,
    [
      ['coins', 5],
      ['trust', 1],
    ],
    '叩き売る',
    [
      ['coins', 10],
      ['trust', -1],
    ],
    ['left'],
    'ライターと、話の続きを。',
  ),
  b(
    159,
    'echo',
    '繰り返す',
    ['time', 'person'],
    ['WIL'],
    2,
    [
      ['mimic', 0.5],
      ['calm', 1],
    ],
    '復唱',
    [
      ['mimic', 0.8],
      ['cost', 0, 1],
    ],
    ['quiet'],
    '相手の言葉を、そのまま返す。',
  ),
  b(
    160,
    'gift',
    '贈り物',
    ['trust', 'person', 'private'],
    ['WIL'],
    2,
    [
      ['trust', 2],
      ['coins', -4],
      ['host', -1],
    ],
    '押し付ける',
    [
      ['trust', 1],
      ['host', 1],
    ],
    ['trusted'],
    '包み紙の分だけ、気持ちが伝わる。',
  ),
  // ─── 161〜167：流用。持っているだけで、余ったもの・払ったもの・受けたものを
  //     別の通貨に換える。職の本来の用途を、まったく別の勝ち筋へずらす部品 ───
  b(
    161,
    'overdose',
    '過剰な手当て',
    ['body', 'trust'],
    ['VIT'],
    3,
    [['heal', 5]],
    '手当てを押し付ける',
    [
      ['heal', 7],
      ['cost', 0, 2],
    ],
    ['quiet'],
    '包帯を巻く手が、止まらない。',
    'uncommon',
    {
      passive: [
        {
          rule: 'overheal',
          fn: (_c, v) => v + 0.8,
          text: '流用：溢れた回復 ×0.8 が相手の体力を削る',
        },
      ],
    },
  ),
  b(
    162,
    'stand',
    '立ち尽くす',
    ['body', 'time'],
    ['DEF'],
    4,
    [['guard', { n: 4, s: 'DEF' }]],
    '根を張る',
    [
      ['guard', { n: 6, s: 'DEF' }],
      ['cost', 0, 1],
    ],
    ['win'],
    '動かない人間は、いずれ景色になる。',
    'uncommon',
    {
      passive: [
        {
          rule: 'guardSpill',
          fn: (_c, v) => v + 0.34,
          text: '流用：手番の終わりに残った守りの 1/3 が信頼になる',
        },
      ],
    },
  ),
  b(
    163,
    'tip',
    '心付け',
    ['public', 'private'],
    ['INT'],
    3,
    [
      ['coins', -8],
      ['trust', 1],
    ],
    'ばら撒く',
    [
      ['coins', -16],
      ['host', 1],
    ],
    ['trusted'],
    '多すぎる心付けは、侮辱になる。',
    'uncommon',
    {
      passive: [
        {
          rule: 'coinBurn',
          fn: (_c, v) => v + 0.5,
          text: '流用：遭遇で払った金の半分が、相手の意志を折る',
        },
      ],
    },
  ),
  b(
    164,
    'rumor',
    '作り話',
    ['private', 'public'],
    ['INT'],
    3,
    [['lie', 2]],
    '尾ひれ',
    [['lie', 3, -10]],
    ['lieKept'],
    '誰も確かめない話ほど、よく回る。',
    'uncommon',
    {
      passive: [
        {
          rule: 'lieEcho',
          fn: (_c, v) => v + 1,
          text: '流用：嘘で得た信頼と同じだけ、相手の意志を削る',
        },
      ],
    },
  ),
  b(
    165,
    'picklock',
    'ピッキング',
    ['private', 'tech'],
    ['AGI'],
    3,
    [['expose', 2], ['see']],
    'こじ開ける',
    [
      ['expose', 3],
      ['host', 2],
    ],
    ['left'],
    '開けられるが、開けない。',
    'uncommon',
    {
      passive: [
        { rule: 'leaveChance', fn: (_c, v) => (v > 0 ? v + 15 : v), text: '去る +15%' },
        {
          rule: 'openSpill',
          fn: (_c, v) => v + 1,
          text: '流用：去る率が 100% を超えた 10% ごとに、毎手番 相手の守り −1',
        },
      ],
    },
  ),
  b(
    166,
    'endure',
    '耐える',
    ['body', 'memory'],
    ['DEF'],
    3,
    [
      ['guard', { n: 3, s: 'DEF' }],
      ['calm', 1],
    ],
    '歯を食いしばる',
    [
      ['guard', 5],
      ['cost', 1],
    ],
    ['win'],
    '殴られているうちに、相手のほうが疲れてくる。',
    'uncommon',
    {
      passive: [
        {
          rule: 'absorb',
          fn: (_c, v) => v + 0.5,
          text: '流用：守りで受け止めた傷の半分だけ、相手の意志が折れる',
        },
      ],
    },
  ),
  b(
    167,
    'regard',
    '見つめ続ける',
    ['gaze', 'trust'],
    ['INT'],
    4,
    [['see'], ['calm', 1]],
    '目を離さない',
    [['see'], ['host', 1]],
    ['trusted'],
    '測るように見ていたはずが、いつのまにか。',
    'uncommon',
    {
      passive: [
        { rule: 'seenTrust', fn: (_c, v) => v + 2, text: '流用：本当の予告を見るたび、信頼 +2' },
      ],
    },
  ),
];
