import type { ItemDef } from './defs';

/** 所持品。タグごとにカードの回数を戻すものと、体と心を戻すもの。 */
export const ITEM_LIST: readonly ItemDef[] = [
  {
    id: 'notebook',
    name: '手帳',
    text: '［視線］［公開情報］のカードの回数 +2。',
    refill: { tags: ['gaze', 'public'], n: 2 },
    price: 30,
    flavor: '前の持ち主の字で、角度と距離が書いてある。',
  },
  {
    id: 'cigarette',
    name: '煙草',
    text: '［記憶］［時間］のカードの回数 +2、精神 +3。',
    refill: { tags: ['memory', 'time'], n: 2 },
    heal: { mind: 3 },
    price: 25,
    flavor: 'PHILLIES。最後の一本。',
  },
  {
    id: 'bandage',
    name: '包帯',
    text: '体力 +10。',
    heal: { hp: 10 },
    price: 20,
    flavor: '少し、足りない長さ。',
  },
  {
    id: 'whisky',
    name: 'ウイスキー',
    text: '［人物］［信頼］のカードの回数 +2。',
    refill: { tags: ['person', 'trust'], n: 2 },
    price: 30,
    flavor: '口が軽くなる。',
  },
  {
    id: 'brass',
    name: 'メリケンサック',
    text: '［身体］のカードの回数 +2。',
    refill: { tags: ['body'], n: 2 },
    price: 30,
    flavor: '指に、ちょうど合う。',
  },
  {
    id: 'bus-ticket',
    name: '回数券',
    text: '［場所］のカードの回数 +1。',
    refill: { tags: ['place'], n: 1 },
    price: 26,
    flavor: '終バスは、もう出た。',
  },
  {
    id: 'coffee',
    name: 'コーヒー',
    text: '精神 +8。',
    heal: { mind: 8 },
    price: 18,
    flavor: '深夜の食堂の、煮詰まった一杯。',
  },
  {
    id: 'radio',
    name: 'トランジスタ',
    text: '［技術］［私的情報］のカードの回数 +2。',
    refill: { tags: ['tech', 'private'], n: 2 },
    price: 32,
    flavor: '周波数の合間に、誰かの声。',
  },
  {
    id: 'badge-pin',
    name: '襟章',
    text: '［制度］［夜］のカードの回数 +2。',
    refill: { tags: ['institution', 'night'], n: 2 },
    price: 32,
    flavor: '裏の番号は削ってある。',
  },
  {
    id: 'photo',
    name: '古い写真',
    text: 'すべてのカードの回数 +1。',
    refill: { tags: [], n: 1 },
    price: 55,
    flavor: '裏に、日付だけ。',
  },
  // ─── その場で（向き合っているあいだ、手番を使わずに） ─────────────
  {
    id: 'smoke',
    name: '煙玉',
    text: '',
    fx: [['stun']],
    price: 34,
    flavor: '祭りの夜店で、三つで百円だった。',
  },
  {
    id: 'bottle',
    name: '割れた瓶',
    text: '',
    fx: [['hit', 8, true]],
    price: 28,
    flavor: '口のところだけが、まだ鋭い。',
  },
  {
    id: 'card-case',
    name: '名刺入れ',
    text: '',
    fx: [['trust', 3]],
    uses: 2,
    price: 30,
    flavor: '肩書きだけが、立派な名刺。',
  },
  {
    id: 'old-map',
    name: '古い間取り図',
    text: '',
    fx: [['clue', 1]],
    uses: 2,
    price: 30,
    flavor: '建て増しの前の線が、薄く残っている。',
  },
  {
    id: 'salt',
    name: '塩',
    text: '',
    fx: [['cut', 5]],
    uses: 2,
    price: 24,
    flavor: '戸口に盛っておくと、少しは効く。',
  },
  {
    id: 'flashlight',
    name: '懐中電灯',
    text: '',
    fx: [['see'], ['expose', 2]],
    uses: 3,
    price: 36,
    flavor: '電池は、あと少し。',
  },
  {
    id: 'blanket',
    name: '毛布',
    text: '',
    fx: [
      ['guard', 8],
      ['calm', 4],
    ],
    uses: 2,
    price: 30,
    flavor: '防災用。まだ折り目がついている。',
  },
  {
    id: 'hymnal',
    name: '讃美歌集',
    text: '',
    fx: [['calm', 10]],
    price: 22,
    flavor: '一番だけ、歌える。',
  },
  {
    id: 'keyring',
    name: '鍵束',
    text: '',
    fx: [['leave']],
    price: 40,
    flavor: 'どの扉のものか、もう分からない鍵ばかり。',
  },
  {
    id: 'perfume',
    name: '香水',
    text: '',
    fx: [
      ['host', -3],
      ['trust', 1],
    ],
    uses: 2,
    price: 26,
    flavor: '名前を言えない花の匂い。',
  },
  {
    id: 'newspaper',
    name: '朝刊',
    text: '',
    fx: [
      ['clue', 1],
      ['break', 3],
    ],
    price: 20,
    flavor: 'まだ日付の来ていない朝刊。',
  },
  {
    id: 'brass-knuckle',
    name: '鉄の指輪',
    text: '',
    fx: [['hit', 5]],
    uses: 3,
    price: 34,
    flavor: '指に、ちょうど合う。',
  },
  {
    id: 'recorder',
    name: '録音機',
    text: '',
    fx: [['note']],
    uses: 2,
    price: 32,
    flavor: 'テープの頭に、誰かの咳が入っている。',
  },
  {
    id: 'whistle',
    name: '呼子笛',
    text: '',
    fx: [
      ['break', 6],
      ['host', 2],
    ],
    price: 22,
    flavor: '吹けば、誰かが振り返る。',
  },
  {
    id: 'candy',
    name: '薄荷飴',
    text: '',
    fx: [['heal', 4, 4]],
    uses: 3,
    price: 18,
    flavor: '缶の底で、白く粉を吹いている。',
  },
  {
    id: 'chalk',
    name: 'チョーク',
    text: '',
    fx: [['mimic', 0.6]],
    price: 26,
    flavor: '床に、さっきの手順を書き写す。',
  },
];
