import type { ItemDef } from './defs';

/**
 * 持ち物。どれも、向き合っていないときに「その場で」使う。使いどころで三つに
 * 分かれる（向き合っているあいだだけ、休憩所でだけ、という品は無い）。
 *
 *   休む  体と心、札一枚の回数を戻す
 *   備える  次に出会う相手との遭遇の初めに効く（煙玉を握って次の部屋へ入る）
 *   探る  その階を探る。出来事が起きるか、何かが見つかるか、誰かに気づかれる
 */
export const ITEM_LIST: readonly ItemDef[] = [
  // ─── 休む ─────────────────────────────────────────────────
  {
    id: 'bandage',
    kind: 'rest',
    name: '包帯',
    text: '体力 +10。',
    heal: { hp: 10 },
    price: 20,
    flavor: '少し、足りない長さ。',
  },
  {
    id: 'coffee',
    kind: 'rest',
    name: 'コーヒー',
    text: '精神 +8。',
    heal: { mind: 8 },
    price: 18,
    flavor: '深夜の食堂の、煮詰まった一杯。',
  },
  {
    id: 'candy',
    kind: 'rest',
    name: '薄荷飴',
    text: '体力 +4、精神 +4。',
    heal: { hp: 4, mind: 4 },
    uses: 3,
    price: 18,
    flavor: '缶の底で、白く粉を吹いている。',
  },
  {
    id: 'blanket',
    kind: 'rest',
    name: '毛布',
    text: '体力 +6、精神 +6。',
    heal: { hp: 6, mind: 6 },
    uses: 2,
    price: 30,
    flavor: '防災用。まだ折り目がついている。',
  },
  {
    id: 'hymnal',
    kind: 'rest',
    name: '讃美歌集',
    text: '精神 +10。',
    heal: { mind: 10 },
    price: 22,
    flavor: '一番だけ、歌える。',
  },
  {
    id: 'cigarette',
    kind: 'rest',
    name: '煙草',
    text: '［記憶］か［時間］の札一枚の回数 +2、精神 +3。',
    refill: { tags: ['memory', 'time'], n: 2 },
    heal: { mind: 3 },
    price: 25,
    flavor: 'PHILLIES。最後の一本。',
  },
  {
    id: 'notebook',
    kind: 'rest',
    name: '手帳',
    text: '［視線］か［公開情報］の札一枚の回数 +2。',
    refill: { tags: ['gaze', 'public'], n: 2 },
    price: 30,
    flavor: '前の持ち主の字で、角度と距離が書いてある。',
  },
  {
    id: 'whisky',
    kind: 'rest',
    name: 'ウイスキー',
    text: '［人物］か［信頼］の札一枚の回数 +2。',
    refill: { tags: ['person', 'trust'], n: 2 },
    price: 30,
    flavor: '口が軽くなる。',
  },
  {
    id: 'brass',
    kind: 'rest',
    name: 'メリケンサック',
    text: '［身体］の札一枚の回数 +2。',
    refill: { tags: ['body'], n: 2 },
    price: 30,
    flavor: '指に、ちょうど合う。',
  },
  {
    id: 'bus-ticket',
    kind: 'rest',
    name: '回数券',
    text: '［場所］の札一枚の回数 +2。',
    refill: { tags: ['place'], n: 2 },
    price: 26,
    flavor: '終バスは、もう出た。',
  },
  {
    id: 'radio',
    kind: 'rest',
    name: 'トランジスタ',
    text: '［技術］か［私的情報］の札一枚の回数 +2。',
    refill: { tags: ['tech', 'private'], n: 2 },
    price: 32,
    flavor: '周波数の合間に、誰かの声。',
  },
  {
    id: 'badge-pin',
    kind: 'rest',
    name: '襟章',
    text: '［制度］か［夜］の札一枚の回数 +2。',
    refill: { tags: ['institution', 'night'], n: 2 },
    price: 32,
    flavor: '裏の番号は削ってある。',
  },
  {
    id: 'photo',
    kind: 'rest',
    name: '古い写真',
    text: 'いちばん減っている札が一枚、満ちる。',
    refill: { tags: [], n: 99 },
    price: 55,
    flavor: '裏に、日付だけ。',
  },
  // 代償つき：いま満ちる代わりに、次の何戦かに反動が残る（道の読みの見込みが変わる）。
  {
    id: 'stimulant',
    kind: 'rest',
    name: '気付け薬',
    text: '体力と精神が満ちる。代償：次の三戦、反動（受ける一撃 +2、脅し +1）。',
    heal: { hp: 99, mind: 99 },
    cost: 3,
    price: 58,
    flavor: '瓶の底に、溶け残った白い粉。',
  },
  {
    id: 'painkiller',
    kind: 'rest',
    name: '鎮痛剤',
    text: '体力 +24。代償：次の二戦、反動（受ける一撃 +2、脅し +1）。',
    heal: { hp: 24 },
    cost: 2,
    price: 30,
    flavor: '効いているあいだは、どこが痛かったか忘れる。',
  },
  {
    id: 'smelling-salts',
    kind: 'rest',
    name: '気付け塩',
    text: '精神 +24。代償：次の二戦、反動（受ける一撃 +2、脅し +1）。',
    heal: { mind: 24 },
    cost: 2,
    price: 30,
    flavor: '鼻の奥に、冬が刺さる。',
  },
  // ─── 備える（次の遭遇の初めに） ─────────────────────────────
  {
    id: 'smoke',
    kind: 'prep',
    name: '煙玉',
    text: '次の相手は、最初の手番に動けない。',
    prep: [['stun']],
    price: 34,
    flavor: '祭りの夜店で、三つで百円だった。',
  },
  {
    id: 'bottle',
    kind: 'prep',
    name: '割れた瓶',
    text: '次の相手の体力 −8（守りを貫く）。',
    prep: [['hit', 8, true]],
    price: 28,
    flavor: '口のところだけが、まだ鋭い。',
  },
  {
    id: 'brass-knuckle',
    kind: 'prep',
    name: '鉄の指輪',
    text: '次の相手の体力 −5。',
    prep: [['hit', 5]],
    uses: 3,
    price: 34,
    flavor: '指に、ちょうど合う。',
  },
  {
    id: 'whistle',
    kind: 'prep',
    name: '呼子笛',
    text: '次の相手の意志 −6、敵意 +2。',
    prep: [
      ['break', 6],
      ['host', 2],
    ],
    price: 22,
    flavor: '吹けば、誰かが振り返る。',
  },
  {
    id: 'card-case',
    kind: 'prep',
    name: '名刺入れ',
    text: '次の相手の信頼 +3。',
    prep: [['trust', 3]],
    uses: 2,
    price: 30,
    flavor: '肩書きだけが、立派な名刺。',
  },
  {
    id: 'perfume',
    kind: 'prep',
    name: '香水',
    text: '次の相手の敵意 −3、信頼 +1。',
    prep: [
      ['host', -3],
      ['trust', 1],
    ],
    uses: 2,
    price: 26,
    flavor: '名前を言えない花の匂い。',
  },
  {
    id: 'old-map',
    kind: 'prep',
    name: '古い間取り図',
    text: '次の相手の手がかりを一つ見る。',
    prep: [['clue', 1]],
    uses: 2,
    price: 30,
    flavor: '建て増しの前の線が、薄く残っている。',
  },
  {
    id: 'newspaper',
    kind: 'prep',
    name: '朝刊',
    text: '次の相手の手がかりを一つ見て、意志 −3。',
    prep: [
      ['clue', 1],
      ['break', 3],
    ],
    price: 20,
    flavor: 'まだ日付の来ていない朝刊。',
  },
  {
    id: 'flashlight',
    kind: 'prep',
    name: '懐中電灯',
    text: '次の相手の本当の予告を見て、手の内を 2 暴く。',
    prep: [['see'], ['expose', 2]],
    uses: 3,
    price: 36,
    flavor: '電池は、あと少し。',
  },
  {
    id: 'salt',
    kind: 'prep',
    name: '塩',
    text: '次の相手の最初の手を 5 弱める。',
    prep: [['cut', 5]],
    uses: 2,
    price: 24,
    flavor: '戸口に盛っておくと、少しは効く。',
  },
  // ─── 探る（その階で、何かが起きるかもしれない） ────────────────
  {
    id: 'keyring',
    kind: 'seek',
    name: '鍵束',
    text: '閉まった扉を開けて回る。何かが見つかりやすい（1 時間）。',
    seek: { story: 0.25, find: 0.55 },
    uses: 2,
    price: 40,
    flavor: 'どの扉のものか、もう分からない鍵ばかり。',
  },
  {
    id: 'recorder',
    kind: 'seek',
    name: '録音機',
    text: '物陰の声を拾う。出来事が起きやすい（1 時間）。',
    seek: { story: 0.6, find: 0.2 },
    uses: 2,
    price: 32,
    flavor: 'テープの頭に、誰かの咳が入っている。',
  },
  {
    id: 'chalk',
    kind: 'seek',
    name: 'チョーク',
    text: '床に印をつけて歩く。誰にも気づかれない（1 時間）。',
    seek: { story: 0.4, find: 0.35, quiet: true },
    uses: 2,
    price: 26,
    flavor: '床に、さっきの手順を書き写す。',
  },
];
