import type { ComboDef, PassiveSpec, PermDef } from './defs';
import { breakFoe, hitFoe, hostile, trust } from '../sim/ops';
import type { Tx } from '../core/tx';

/**
 * PERMANENT。使わないカード。手に入れた瞬間から効き続け、並べればそのまま
 * 「今回、何を経験してきたか」になる。
 *
 * 人物もみな同じ札を持っていて、手がかりとして見えると攻め筋になる
 * （exploit）。暴けば、そのうち何枚かを自分のものとして持ち帰れる。
 */

/** 疑う目・血の匂い・閉ざした心は、信頼の伸びを 1 削る（重ねても 1）。 */
const DISTRUST: PassiveSpec = {
  key: 'distrust',
  rule: 'trust',
  fn: (_c, v) => (v > 0 ? Math.max(0, v - 1) : v),
  text: '信頼の伸び −1',
};

export const PERM_LIST: readonly PermDef[] = [
  // ─── 生まれと、探しているもの ───
  {
    id: 'promise',
    name: '彼女との約束',
    kind: 'bond',
    tags: ['trust', 'person', 'memory'],
    text: '彼女を探している。最後の相手との結末が変わる。',
    value: 80,
    tags: ['her'],
    echo: { label: '約束を思い出させる', kind: 'threat', power: 5 },
    flavor: '「見つけたら、明かりをつけて」',
  },
  {
    id: 'old-wound',
    name: '古傷',
    kind: 'wound',
    tags: ['body'],
    text: 'VIT −1。体力が半分を切ると ATK +3。',
    mods: { VIT: -1 },
    dyn: (w, s) => (s === 'ATK' && w.you.hp * 2 < 16 + 4 * (w.you.innate.VIT + w.you.growth.VIT) ? 3 : 0),
    value: 10,
    echo: { label: '古傷を抉る', kind: 'strike', power: 7 },
    flavor: '雨の前に、いつも疼く。',
  },
  {
    id: 'accident',
    name: '事故の記憶',
    kind: 'memory',
    tags: ['memory', 'time'],
    text: 'WIL +2。特定の場所で出来事が変わる。',
    mods: { WIL: 2 },
    value: 30,
    tags: ['accident'],
    echo: { label: 'あの事故を映す', kind: 'threat', power: 8 },
    flavor: 'ブレーキの音は、まだ止んでいない。',
  },
  {
    id: 'habit-measure',
    name: '測量の癖',
    kind: 'trait',
    tags: ['place', 'gaze'],
    text: 'INT +1。観察の判定 +5。',
    mods: { INT: 1 },
    passive: [{ rule: 'checkChance', when: (c) => !!c.stat?.includes('INT'), fn: (_c, v) => v + 5, text: 'INT 判定 +5%' }],
    value: 20,
    echo: { label: '距離を測る', kind: 'strike', power: 5 },
    flavor: '部屋に入ると、まず四隅の角度を見る。',
  },
  // ─── カードの使い方から生まれるもの ───
  {
    id: 'belief',
    name: '思い込み',
    kind: 'state',
    tags: ['private'],
    text: 'INT −1。凝視が残した、確かめていない確信。',
    mods: { INT: -1 },
    value: 0,
    bad: true,
    echo: { label: '思い込みを突く', kind: 'threat', power: 6 },
    flavor: 'そうに違いない、と思った瞬間から、見えなくなる。',
  },
  {
    id: 'habit-observe',
    name: '習慣的観察',
    kind: 'trait',
    tags: ['gaze'],
    text: 'INT +1。層が替わるたび、観察の回数が 1 戻る。',
    mods: { INT: 1 },
    value: 25,
    echo: { label: '見返してくる', kind: 'threat', power: 5 },
    flavor: '休ませた目は、よく見える。',
  },
  {
    id: 'liar',
    name: '虚言癖',
    kind: 'trait',
    tags: ['private', 'public'],
    text: '嘘の判定 +10。WIL −1。',
    mods: { WIL: -1 },
    passive: [{ rule: 'lieChance', fn: (_c, v) => v + 10, text: '嘘 +10%' }],
    value: 15,
    bad: true,
    echo: { label: 'あなたの嘘を並べる', kind: 'threat', power: 7 },
    flavor: '口が先に動く。',
  },
  {
    id: 'temper',
    name: '短気',
    kind: 'trait',
    tags: ['body'],
    text: 'ATK +1、WIL −1。遭遇の初めに相手の敵意 +1。',
    mods: { ATK: 1, WIL: -1 },
    passive: [{ rule: 'startHostility', fn: (_c, v) => v + 1, text: '遭遇の初めの敵意 +1' }],
    value: 5,
    bad: true,
    echo: { label: '怒らせる', kind: 'strike', power: 7 },
    flavor: '机を叩く音で、話が終わる。',
  },
  {
    id: 'runaway',
    name: '逃げ癖',
    kind: 'trait',
    tags: ['place'],
    text: 'AGI +1、WIL −1。',
    mods: { AGI: 1, WIL: -1 },
    value: 5,
    bad: true,
    echo: { label: '背中を見せさせる', kind: 'threat', power: 6 },
    flavor: '出口に近い席に、いつも座る。',
  },
  {
    id: 'closed-heart',
    name: '閉ざした心',
    kind: 'trait',
    tags: ['private'],
    text: '遭遇の初めに心の構え 3。打ち解けるときの信頼の伸び −1。',
    passive: [DISTRUST],
    triggers: [{ on: 'enc.start', run: (tx) => tx.emit({ type: 'enc.you', field: 'calm', n: 3 }), text: '遭遇の初めに心の構え 3' }],
    value: 5,
    bad: true,
    echo: { label: '扉を叩く', kind: 'threat', power: 6 },
    flavor: '誰も入れなければ、誰にも壊されない。',
  },
  {
    id: 'past-bound',
    name: '過去に囚われる',
    kind: 'state',
    tags: ['memory', 'time'],
    text: 'WIL +1、INT −1。',
    mods: { WIL: 1, INT: -1 },
    value: 5,
    bad: true,
    echo: { label: '過去へ引き戻す', kind: 'threat', power: 8 },
    flavor: '時計は、あの時刻で止まっている。',
  },
  {
    id: 'blood',
    name: '血の味',
    kind: 'trait',
    tags: ['body'],
    text: 'ATK +2。人はそれを嗅ぎ取る（信頼の伸び −1）。',
    mods: { ATK: 2 },
    value: 10,
    bad: true,
    echo: { label: '血を思い出させる', kind: 'strike', power: 9 },
    passive: [DISTRUST],
    flavor: '口の中の鉄の味が、消えない。',
  },
  {
    id: 'guilt',
    name: '罪悪感',
    kind: 'state',
    tags: ['memory'],
    text: 'WIL −1。',
    mods: { WIL: -1 },
    value: 0,
    bad: true,
    echo: { label: '暴いた墓を見せる', kind: 'threat', power: 9 },
    flavor: '眠っていたものは、眠らせておけばよかった。',
  },
  {
    id: 'suspicion',
    name: '猜疑心',
    kind: 'trait',
    tags: ['gaze', 'private'],
    text: '嘘の予告が透けて見える。信頼を得にくい（伸び −1）。',
    value: 20,
    echo: { label: '疑いを返す', kind: 'threat', power: 6 },
    passive: [DISTRUST, { rule: 'intentVisible', fn: () => 1, text: '嘘の予告が見える' }],
    flavor: '親切な顔ほど、よく見る。',
  },
  {
    id: 'fear',
    name: '怖れ',
    kind: 'wound',
    tags: ['body'],
    text: '精神への傷 +1。',
    value: 0,
    bad: true,
    echo: { label: '怖れを呼び起こす', kind: 'threat', power: 8 },
    passive: [{ rule: 'threatTaken', fn: (_c, v) => v + 1, text: '精神への傷 +1' }],
    flavor: '暗い角を曲がるたびに、息を止める。',
  },
  {
    id: 'insomnia',
    name: '不眠',
    kind: 'state',
    tags: ['night', 'time'],
    text: 'WIL −1。休むと、カードの回数がさらに 1 戻る。',
    mods: { WIL: -1 },
    value: 10,
    echo: { label: '眠らせない', kind: 'threat', power: 6 },
    flavor: '夜は長い。使い道はある。',
  },
  // ─── 人から持ち帰るもの（手がかり） ───
  {
    id: 'knee',
    name: '古傷（左膝）',
    kind: 'wound',
    tags: ['body'],
    text: '左膝をかばって立つ。',
    value: 0,
    exploit: { text: '押すと 1.5 倍', press: 1.5 },
    flavor: '踏み込めない側がある。',
  },
  {
    id: 'daughter-photo',
    name: '娘の写真',
    kind: 'bond',
    tags: ['person', 'trust'],
    text: 'WIL +1。守るものがある。',
    mods: { WIL: 1 },
    value: 25,
    exploit: { text: '話すと信頼の伸びが 2 倍', talk: 2 },
    echo: { label: '写真を見せる', kind: 'threat', power: 6 },
    flavor: '財布の奥に、角の折れた一枚。',
  },
  {
    id: 'saw-her',
    name: 'あの夜、彼女を見た',
    kind: 'memory',
    tags: ['memory', 'night'],
    text: 'INT +1。彼女の足取りの一つ目。',
    mods: { INT: 1 },
    value: 40,
    tags: ['her'],
    exploit: { text: '見えると信頼 +1（話したがっていた）', show: (tx: Tx) => trust(tx, 1) },
    echo: { label: 'あの夜を語る', kind: 'threat', power: 7 },
    flavor: '「十一時過ぎ。角の食堂の前を、北へ」',
  },
  {
    id: 'closing-time',
    name: '閉店時間',
    kind: 'state',
    tags: ['time'],
    text: '閉店を急いでいる。',
    value: 0,
    exploit: { text: '威圧が 1.3 倍', force: 1.3 },
    flavor: '時計を三度見た。',
  },
  {
    id: 'phillies',
    name: '煙草の銘柄',
    kind: 'memory',
    tags: ['place'],
    text: '同じ煙草を吸う者どうし。',
    value: 0,
    exploit: { text: '話すと信頼の伸びが 1.5 倍', talk: 1.5 },
    flavor: '看板と同じ名前の。',
  },
  {
    id: 'shaft-key',
    name: '縦坑の鍵',
    kind: 'state',
    tags: ['place', 'private'],
    text: '層の夜が 1 時間早く始まる（下りるのが速い）。',
    value: 45,
    exploit: { text: '見えると敵意 −1（鍵を気にしている）', show: (tx: Tx) => hostile(tx, -1) },
    echo: { label: '鍵を取り上げる', kind: 'strike', power: 6 },
    flavor: '真鍮の、重い鍵。',
  },
  {
    id: 'drink',
    name: '酒',
    kind: 'state',
    tags: ['body'],
    text: '酔っている。',
    value: 0,
    exploit: { text: '嘘が通りやすい', lie: 1.5 },
    flavor: 'グラスの底が、もう三回見えた。',
  },
  {
    id: 'lost-son',
    name: '息子を亡くした',
    kind: 'memory',
    tags: ['memory', 'person'],
    text: 'WIL +1。他人の喪失がわかる。',
    mods: { WIL: 1 },
    value: 20,
    tags: ['grief'],
    exploit: { text: '話すと信頼の伸びが 1.5 倍', talk: 1.5 },
    echo: { label: '喪失を重ねる', kind: 'threat', power: 7 },
    flavor: '同じ年頃の若者を見ると、黙る。',
  },
  {
    id: 'false-alibi',
    name: '偽のアリバイ',
    kind: 'memory',
    tags: ['private'],
    text: 'あの夜、本当はどこにいたのか。',
    value: 0,
    exploit: { text: '威圧が 1.5 倍', force: 1.5 },
    flavor: '話すたびに、店の名前が変わる。',
  },
  {
    id: 'hunger',
    name: '空腹',
    kind: 'state',
    tags: ['body'],
    text: '腹を空かせている。',
    value: 0,
    exploit: { text: '見えると敵意 −2', show: (tx: Tx) => hostile(tx, -2) },
    flavor: 'あばらが浮いている。',
  },
  {
    id: 'hurt-paw',
    name: '傷ついた足',
    kind: 'wound',
    tags: ['body'],
    text: '前足を引きずっている。',
    value: 0,
    exploit: { text: '押すと 1.5 倍', press: 1.5 },
    flavor: '踏み出すたびに、小さく鳴く。',
  },
  {
    id: 'dog-friend',
    name: '犬の友',
    kind: 'bond',
    tags: ['trust', 'place'],
    text: 'AGI +1。琥珀層の犬が、あなたを覚えている。',
    mods: { AGI: 1 },
    value: 30,
    echo: { label: '吠える', kind: 'threat', power: 4 },
    flavor: '後ろを、少し離れてついてくる。',
  },
  {
    id: 'watch-debt',
    name: '夜警の借り',
    kind: 'bond',
    tags: ['trust', 'institution'],
    text: '遭遇の初めに守り 4（誰かが背中を見ている）。',
    triggers: [{ on: 'enc.start', run: (tx) => tx.emit({ type: 'enc.you', field: 'guard', n: 4 }), text: '遭遇の初めに守り 4' }],
    value: 25,
    echo: { label: '借りを取り立てる', kind: 'strike', power: 6 },
    flavor: '「次に困ったら、灯りを二度点けろ」',
  },
  {
    id: 'regular-seat',
    name: '常連の席',
    kind: 'bond',
    tags: ['place', 'trust'],
    text: '食堂で休むと、さらに 10 回復する。',
    value: 20,
    passive: [{ rule: 'restHeal', fn: (_c, v) => v + 10, text: '休むと +10 回復' }],
    flavor: 'カウンターの、端から二つ目。',
  },
  {
    id: 'badge',
    name: '奪った警察章',
    kind: 'state',
    tags: ['institution'],
    text: 'DEF +1。遭遇の初めに相手の敵意 −1（権威に見える）。',
    mods: { DEF: 1 },
    passive: [{ rule: 'startHostility', fn: (_c, v) => v - 1, text: '遭遇の初めの敵意 −1' }],
    value: 30,
    echo: { label: '偽の権威を剥ぐ', kind: 'threat', power: 6 },
    flavor: '番号は、削っておいた。',
  },
  {
    id: 'mirror',
    name: '鏡',
    kind: 'trait',
    tags: ['gaze'],
    text: 'あなたの真似をする。',
    value: 0,
    exploit: { text: '見えると相手の意志 −4', show: (tx: Tx) => breakFoe(tx, 4) },
    flavor: '窓に映っているのは、どちらか。',
  },
  {
    id: 'cold-coffee',
    name: '冷めたコーヒー',
    kind: 'memory',
    tags: ['time'],
    text: '誰かを待っている。',
    value: 0,
    exploit: { text: '話すと信頼の伸びが 1.5 倍', talk: 1.5 },
    flavor: '手をつけていない。',
  },
  {
    id: 'her-letter',
    name: '彼女の手紙',
    kind: 'memory',
    tags: ['memory', 'private'],
    text: 'WIL +1、INT +1。彼女の足取りの一つ。',
    mods: { WIL: 1, INT: 1 },
    value: 50,
    tags: ['her'],
    echo: { label: '手紙を読み上げる', kind: 'threat', power: 8 },
    flavor: '「深く掘っても、わたしはいない」',
  },
  {
    id: 'catalog',
    name: '目録',
    kind: 'memory',
    tags: ['institution', 'public'],
    text: 'すべてを覚えている。',
    value: 0,
    exploit: { text: '威圧が 1.3 倍（矛盾を突ける）', force: 1.3 },
    flavor: '番号のないものは、存在しない。',
  },
  {
    id: 'redacted',
    name: '黒塗りの頁',
    kind: 'memory',
    tags: ['private', 'institution'],
    text: '隠したことがある。',
    value: 0,
    exploit: { text: '見えると相手の意志 −5', show: (tx: Tx) => breakFoe(tx, 5) },
    flavor: '黒い帯の下に、名前がある。',
  },
  {
    id: 'her-file',
    name: '彼女のファイル',
    kind: 'memory',
    tags: ['public', 'memory'],
    text: 'INT +2。彼女の足取りの一つ。',
    mods: { INT: 2 },
    value: 50,
    tags: ['her'],
    echo: { label: '記録を突きつける', kind: 'threat', power: 8 },
    flavor: '最後の頁だけ、日付がない。',
  },
  {
    id: 'fire',
    name: '映写室の火事',
    kind: 'memory',
    tags: ['memory', 'tech'],
    text: 'WIL +1。',
    mods: { WIL: 1 },
    value: 30,
    tags: ['fire'],
    exploit: { text: '見えると相手の意志 −4', show: (tx: Tx) => breakFoe(tx, 4) },
    echo: { label: '炎を映す', kind: 'threat', power: 8 },
    flavor: 'ナイトレートのフィルムは、水の中でも燃える。',
  },
  {
    id: 'last-reel',
    name: '最後のリール',
    kind: 'memory',
    tags: ['memory', 'time'],
    text: '終わりを見ていない。',
    value: 0,
    exploit: { text: '話すと信頼の伸びが 1.5 倍', talk: 1.5 },
    flavor: '缶の封は、切られていない。',
  },
  {
    id: 'flashlight',
    name: '懐中電灯',
    kind: 'state',
    tags: ['gaze', 'night'],
    text: '手元が明るい。',
    value: 0,
    exploit: { text: '押すと 1.3 倍（光の外から）', press: 1.3 },
    flavor: '光の輪の外は、真っ暗だ。',
  },
  {
    id: 'empty-seat',
    name: '空席',
    kind: 'memory',
    tags: ['place', 'memory'],
    text: 'いつも空けてある席がある。',
    value: 0,
    exploit: {
      text: '見えると、話しても咎められなくなる',
      show: (tx: Tx) => tx.emit({ type: 'foe.st', key: 'unhushed', n: 1 }),
    },
    flavor: 'G 列の 7 番。',
  },
  {
    id: 'ticket',
    name: '半券',
    kind: 'state',
    tags: ['time', 'public'],
    text: 'AGI +1。',
    mods: { AGI: 1 },
    value: 20,
    echo: { label: '退場を告げる', kind: 'strike', power: 5 },
    flavor: '最終回の。',
  },
  {
    id: 'paper-diet',
    name: '紙を食む',
    kind: 'state',
    tags: ['body'],
    text: '紙を食べて殖える。',
    value: 0,
    exploit: { text: '押すと 1.5 倍', press: 1.5 },
    flavor: '銀色の、小さな群れ。',
  },
  {
    id: 'black-ink',
    name: '墨',
    kind: 'state',
    tags: ['institution'],
    text: '消すための墨。',
    value: 0,
    exploit: { text: '威圧が 1.5 倍', force: 1.5 },
    flavor: '一行ずつ、丁寧に。',
  },
  {
    id: 'scissors',
    name: '鋏',
    kind: 'state',
    tags: ['tech'],
    text: '切るための鋏。',
    value: 0,
    exploit: { text: '押すと 1.3 倍', press: 1.3 },
    flavor: '刃こぼれしている。',
  },
  {
    id: 'uncut',
    name: '切られなかった場面',
    kind: 'memory',
    tags: ['memory', 'private'],
    text: 'INT +1、WIL +1。',
    mods: { INT: 1, WIL: 1 },
    value: 40,
    echo: { label: '未公開の場面を映す', kind: 'threat', power: 7 },
    flavor: '検閲官がひとつだけ、残しておいた。',
  },
  {
    id: 'voicemail',
    name: '母の留守電',
    kind: 'bond',
    tags: ['person', 'memory'],
    text: 'WIL +1、VIT +1。',
    mods: { WIL: 1, VIT: 1 },
    value: 35,
    exploit: { text: '話すと信頼の伸びが 2 倍', talk: 2 },
    echo: { label: '留守電を再生する', kind: 'threat', power: 7 },
    flavor: '「ごはん、冷蔵庫に入ってるから」',
  },
  {
    id: 'lullaby',
    name: '子守歌',
    kind: 'memory',
    tags: ['memory'],
    text: '眠らせる歌。',
    value: 0,
    exploit: { text: '見えると相手の敵意 −2', show: (tx: Tx) => hostile(tx, -2) },
    flavor: '節だけ覚えている。',
  },
  {
    id: 'illness',
    name: '病',
    kind: 'wound',
    tags: ['body'],
    text: '長くない。',
    value: 0,
    exploit: { text: '威圧が 1.5 倍', force: 1.5 },
    flavor: '咳が、言葉の途中に混じる。',
  },
  {
    id: 'overheat',
    name: '過熱',
    kind: 'state',
    tags: ['tech'],
    text: '熱を持ちすぎている。',
    value: 0,
    exploit: { text: '押すと 1.5 倍', press: 1.5 },
    flavor: '装甲が赤く光っている。',
  },
  {
    id: 'serial',
    name: '製造番号',
    kind: 'memory',
    tags: ['tech', 'public'],
    text: '型番がわかる。',
    value: 0,
    exploit: { text: '見えると相手の体力 −6（弱点の位置）', show: (tx: Tx) => hitFoe(tx, 6, true) },
    flavor: 'RF-0327。',
  },
  {
    id: 'core-sample',
    name: '試料',
    kind: 'state',
    tags: ['place', 'time'],
    text: '地層の標本を抱えている。',
    value: 0,
    exploit: { text: '威圧が 1.3 倍', force: 1.3 },
    flavor: '一本の円柱に、千年。',
  },
  {
    id: 'factory-smell',
    name: '工場の臭い',
    kind: 'memory',
    tags: ['memory', 'place'],
    text: 'VIT +1。どこかで嗅いだ臭い。',
    mods: { VIT: 1 },
    value: 25,
    tags: ['factory'],
    echo: { label: '臭いを嗅がせる', kind: 'threat', power: 7 },
    flavor: '焦げた油と、甘い薬品。',
  },
  {
    id: 'rival-notes',
    name: 'ライバルの手帳',
    kind: 'memory',
    tags: ['private', 'place'],
    text: 'INT +1。もう一人の掘る人の足取りがわかる。',
    mods: { INT: 1 },
    value: 30,
    echo: { label: '先回りする', kind: 'strike', power: 6 },
    flavor: '同じ場所に、同じ印がついている。',
  },
  {
    id: 'resin-shell',
    name: '樹脂の殻',
    kind: 'state',
    tags: ['body'],
    text: '固い殻に覆われている。',
    value: 0,
    exploit: { text: '押すと 1.3 倍（継ぎ目を狙える）', press: 1.3 },
    flavor: '光に透かすと、中が見える。',
  },
  {
    id: 'amber-eye',
    name: '琥珀の目',
    kind: 'state',
    tags: ['gaze'],
    text: 'INT +1。手がかりの数が見える。',
    mods: { INT: 1 },
    value: 35,
    echo: { label: '琥珀越しに見る', kind: 'threat', power: 6 },
    flavor: '閉じ込められた羽が、目の奥で動く。',
  },
  {
    id: 'nighthawk',
    name: '夜の客',
    kind: 'bond',
    tags: ['night', 'person'],
    text: 'WIL +1、DEF +1。',
    mods: { WIL: 1, DEF: 1 },
    value: 30,
    echo: { label: '隣に座る', kind: 'threat', power: 5 },
    flavor: '同じ灯りの下にいた、名前を知らない人。',
  },
  {
    id: 'projected',
    name: '映された記憶',
    kind: 'memory',
    tags: ['memory', 'gaze'],
    text: 'INT +1、WIL +1。',
    mods: { INT: 1, WIL: 1 },
    value: 35,
    echo: { label: 'もう一度映す', kind: 'threat', power: 7 },
    flavor: 'スクリーンの中の自分は、少し若い。',
  },
  // ─── 組み合わせから生まれるもの ───
  {
    id: 'scarred',
    name: '傷だらけの拳',
    kind: 'wound',
    tags: ['body'],
    text: 'ATK +1、DEF +1。',
    mods: { ATK: 1, DEF: 1 },
    value: 25,
    echo: { label: '拳を振るわせる', kind: 'strike', power: 8 },
    flavor: '古傷と血の味が、同じ手に宿った。',
  },
  {
    id: 'hollow-promise',
    name: '空っぽの約束',
    kind: 'state',
    tags: ['private'],
    text: 'WIL −2。嘘で塗った約束。',
    mods: { WIL: -2 },
    value: 0,
    bad: true,
    echo: { label: '約束の嘘を暴く', kind: 'threat', power: 10 },
    flavor: '守るつもりで言った。たぶん。',
  },
  {
    id: 'home',
    name: '帰る場所',
    kind: 'bond',
    tags: ['place', 'trust'],
    text: 'VIT +1、WIL +1。',
    mods: { VIT: 1, WIL: 1 },
    value: 40,
    echo: { label: '帰り道を示す', kind: 'threat', power: 4 },
    flavor: '犬が待っていて、留守電が鳴る家。',
  },
  {
    id: 'two-fires',
    name: 'ふたつの火',
    kind: 'memory',
    tags: ['memory'],
    text: 'WIL +2。',
    mods: { WIL: 2 },
    value: 40,
    echo: { label: '火を重ねる', kind: 'threat', power: 9 },
    flavor: '事故の火と、映写室の火は、同じ色をしていた。',
  },
  {
    id: 'truth',
    name: '真相',
    kind: 'memory',
    tags: ['memory', 'private'],
    text: 'WIL +2、INT +1。事故の夜に何があったか。',
    mods: { WIL: 2, INT: 1 },
    value: 60,
    tags: ['her'],
    echo: { label: '真相を告げる', kind: 'threat', power: 10 },
    flavor: '運転していたのは、あなたではなかった。',
  },
  {
    id: 'false-lead',
    name: '誤った手がかり',
    kind: 'state',
    tags: [],
    text: '執着が見せた幻。',
    value: 0,
    flavor: 'そこには、何もなかった。',
  },
];

export const COMBO_LIST: readonly ComboDef[] = [
  {
    id: 'accident-site',
    name: '事故現場',
    needs: ['accident', 'factory-smell'],
    text: '事故の記憶と工場の臭いが繋がる。「事故現場」の出来事が開く。',
    story: 'accident-site',
  },
  {
    id: 'scarred',
    name: '傷だらけの拳',
    needs: ['old-wound', 'blood'],
    text: '古傷と血の味が、同じ拳に宿る。',
    grant: 'scarred',
  },
  {
    id: 'hollow',
    name: '空っぽの約束',
    needs: ['liar', 'promise'],
    text: '嘘に慣れた口で交わした約束は、中身を失う。',
    grant: 'hollow-promise',
  },
  {
    id: 'her-trail',
    name: '彼女の足取り',
    needs: ['saw-her', 'her-file', 'her-letter'],
    text: '三つの足取りが一本の線になる。「彼女の足取り」の出来事が開く。',
    story: 'her-trail',
  },
  {
    id: 'home',
    name: '帰る場所',
    needs: ['dog-friend', 'voicemail'],
    text: '待っている犬と、鳴り続ける留守電。',
    grant: 'home',
  },
  {
    id: 'two-fires',
    name: 'ふたつの火',
    needs: ['fire', 'accident'],
    text: 'ふたつの火事の記憶が重なる。',
    grant: 'two-fires',
  },
  {
    id: 'confession',
    name: '告解',
    needs: ['guilt', 'lost-son'],
    text: '暴いた墓と、他人の喪失。「告解」の出来事が開く。',
    story: 'confession',
  },
  {
    id: 'deja-vu',
    name: '既視感',
    needs: ['suspicion', 'habit-observe'],
    text: '疑う目と慣れた目が重なる。観察が「既視感」へ変質できる。',
  },
];
