import type { Stat } from '../core/model';
import type { Tag } from '../core/tags';
import { isDeep } from '../core/time';
import type { CardDef, PassiveSpec, Recover, Work } from './defs';
import type { Cond, Fx, Num } from './fx';

/**
 * 100 の作品が、100 枚のカードになる。
 *
 *   絵画 1–25 / 文学・SF 26–55 / 映画 56–80 / 思想・社会科学・建築 81–100
 *
 * どのカードも共通のタグを持ち、出来事・人物・ビルドは同じタグを読む。
 * 使うと効き（READY）、0 回でも使える（SPENT：代償つきの非常手段）。休ませ
 * 続けるか酷使するかで、別の作品へ変質する。枠に入っているだけで規則を
 * 書き換えるもの（passive）と、条件がそろうと現れる隠し効果がある。
 */

const S = (n: number, s: Stat, m = 1): Num => ({ n, s, m });
const P = (n: number, per: Tag, pm = 1): Num => ({ n, per, pm });

type Kind = Work['kind'];

interface Extra {
  alter?: CardDef['alter'];
  shift?: CardDef['shift'];
  hidden?: { id: string; when: Cond; fx: Fx[]; text: string };
  passive?: PassiveSpec[];
  restOnly?: boolean;
}

function w(
  no: number,
  id: string,
  title: string,
  by: string,
  year: number,
  kind: Kind,
  tags: Tag[],
  stats: Stat[],
  uses: number,
  rarity: CardDef['rarity'],
  ready: Fx[],
  spentName: string,
  spent: Fx[],
  recover: Recover[],
  flavor: string,
  x: Extra = {},
): CardDef {
  return {
    id,
    layer: 'archetype',
    no,
    name: title,
    work: { title, by, year, kind },
    tags,
    stats,
    uses,
    rarity,
    ready,
    spentName,
    spent,
    recover: { on: recover, restOnly: x.restOnly },
    alter: x.alter,
    shift: x.shift,
    hidden: x.hidden,
    passive: x.passive,
    since: '1.1.0',
    flavor,
  };
}

const night = (c: { w: { hour: number } }) => isDeep(c.w.hour);
const foeHas = (t: Tag) => (c: { enc?: { foe: { tags: readonly Tag[] } } | null }) =>
  !!c.enc?.foe.tags.includes(t);

export const WORKS: readonly CardDef[] = [
  // ─── 絵画 ──────────────────────────────────────────────────
  w(
    1,
    'joseph',
    '大工の聖ヨセフ',
    'ジョルジュ・ド・ラ・トゥール',
    1642,
    'painting',
    ['body', 'trust', 'night'],
    ['WIL'],
    3,
    'common',
    [
      ['calm', S(3, 'WIL')],
      ['trust', 2],
    ],
    '消えかけた蝋燭',
    [
      ['trust', 1],
      ['cost', 0, 1],
    ],
    ['trusted'],
    '子どもの掲げる蝋燭が、働く手を照らす。',
    {
      passive: [
        { rule: 'turnCalm', when: night, fn: (_c, v) => v + 1, text: '深夜、毎手番 心の構え +1' },
      ],
    },
  ),
  w(
    2,
    'agnus',
    'アグヌス・デイ',
    'フランシスコ・デ・スルバラン',
    1635,
    'painting',
    ['body', 'trust'],
    ['WIL', 'VIT'],
    2,
    'uncommon',
    [
      ['cost', 3],
      ['trust', 4],
    ],
    '縛られた脚',
    [
      ['cost', 5],
      ['trust', 3],
      ['host', -2],
    ],
    ['quiet'],
    '暗闇に、縛られた子羊が一頭。差し出すことで、信じてもらう。',
  ),
  w(
    3,
    'airpump',
    '空気ポンプの中の鳥の実験',
    'ジョセフ・ライト',
    1768,
    'painting',
    ['gaze', 'tech', 'public'],
    ['INT'],
    3,
    'common',
    [
      ['see'],
      [
        'check',
        'INT',
        30,
        [
          ['clue', 1],
          ['break', 3],
        ],
        [['break', 2]],
      ],
    ],
    '真空',
    [
      ['break', S(4, 'INT')],
      ['cost', 0, 2],
    ],
    ['uncover'],
    '蝋燭の光の中で、皆が鳥の最期を見ている。',
    {
      alter: { care: { to: 'revolutions', need: 2 } },
      passive: [
        {
          rule: 'checkChance',
          when: (c) => !!c.stat?.includes('INT'),
          fn: (_c, v) => v + 5,
          text: 'INT 判定 +5%',
        },
      ],
    },
  ),
  w(
    4,
    'meninas',
    'ラス・メニーナス',
    'ディエゴ・ベラスケス',
    1656,
    'painting',
    ['gaze', 'institution', 'person'],
    ['INT'],
    3,
    'uncommon',
    [['see'], ['clue', 1], ['host', -1]],
    '鏡の中の王',
    [['see'], ['clue', 1, true], ['cost', 0, 1]],
    ['uncover'],
    '描く者が、描かれる者を見返している。',
    {
      alter: { secret: { to: 'pope', perms: ['suspicion', 'blood'] } },
      hidden: {
        id: 'meninas-king',
        when: ['foeTag', 'institution'],
        fx: [['clue', 1]],
        text: '相手が［制度］なら、手がかりをもう 1 つ',
      },
    },
  ),
  w(
    5,
    'delft',
    'デルフト眺望',
    'ヨハネス・フェルメール',
    1661,
    'painting',
    ['place', 'time', 'public'],
    ['WIL'],
    3,
    'common',
    [
      ['calm', 4],
      ['heal', 0, 2],
    ],
    '小さな黄色い壁',
    [
      ['heal', 0, 3],
      ['cost', 2],
    ],
    ['newPlace'],
    '雲の影が町を半分だけ覆う朝。',
    { passive: [{ rule: 'restHeal', fn: (_c, v) => v + 5, text: '休むと +5 回復' }] },
  ),
  w(
    6,
    'hunters',
    '雪中の狩人',
    'ピーテル・ブリューゲル',
    1565,
    'painting',
    ['place', 'body', 'time'],
    ['ATK', 'VIT'],
    3,
    'common',
    [
      ['hit', S(4, 'ATK')],
      ['guard', 2],
    ],
    '空の獲物袋',
    [
      ['hit', S(3, 'ATK')],
      ['cost', 2],
    ],
    ['win'],
    '疲れた犬と、坂の下の村の灯り。',
  ),
  w(
    7,
    'wave',
    '神奈川沖浪裏',
    '葛飾北斎',
    1831,
    'painting',
    ['body', 'time', 'public'],
    ['ATK'],
    2,
    'uncommon',
    [
      ['hit', S(6, 'ATK', 1.5)],
      ['host', 2],
    ],
    '崩れる波頭',
    [
      ['hit', S(8, 'ATK', 2)],
      ['cost', 3],
      ['host', 3],
    ],
    ['win'],
    '波の爪の向こうに、小さな山。',
    { alter: { overuse: { to: 'rain', need: 2 } } },
  ),
  w(
    8,
    'may3',
    '1808年5月3日',
    'フランシスコ・デ・ゴヤ',
    1814,
    'painting',
    ['institution', 'body', 'night'],
    ['WIL'],
    2,
    'uncommon',
    [
      ['break', S(5, 'WIL')],
      ['host', 1],
    ],
    '白いシャツ',
    [
      ['break', S(8, 'WIL')],
      ['cost', 0, 3],
    ],
    ['broken'],
    '銃を構える者たちの顔は、描かれていない。',
  ),
  w(
    9,
    'monk',
    '海辺の僧侶',
    'カスパー・ダーヴィト・フリードリヒ',
    1810,
    'painting',
    ['place', 'time', 'memory'],
    ['WIL'],
    4,
    'common',
    [
      ['calm', S(6, 'WIL')],
      ['host', -2],
    ],
    '灰色の海',
    [
      ['calm', 8],
      ['trust', -1],
    ],
    ['quiet'],
    '空と海の境目に、ひとりだけ。',
    {
      alter: { care: { to: 'interior', need: 2 }, overuse: { to: 'icesea', need: 2 } },
      passive: [
        {
          rule: 'calmKeep',
          fn: (_c, v) => Math.max(v, 0.5),
          text: '心の構えが手番をまたいで半分残る',
        },
      ],
    },
  ),
  w(
    10,
    'isle',
    '死の島',
    'アルノルト・ベックリン',
    1880,
    'painting',
    ['place', 'memory', 'time'],
    ['WIL'],
    2,
    'uncommon',
    [['break', S(4, 'WIL')], ['see']],
    '舟渡し',
    [
      ['break', S(7, 'WIL')],
      ['cost', 0, 3],
    ],
    ['newPlace'],
    '白い人影を乗せた舟が、糸杉の島へ。',
    {
      hidden: {
        id: 'isle-accept',
        when: ['lowHp'],
        fx: [['calm', 10]],
        text: '体力が 1/3 を切っていれば、心の構え 10',
      },
    },
  ),
  w(
    11,
    'icesea',
    '氷の海',
    'カスパー・ダーヴィト・フリードリヒ',
    1824,
    'painting',
    ['place', 'time', 'body'],
    ['WIL', 'DEF'],
    3,
    'uncommon',
    [
      ['guard', S(6, 'DEF')],
      ['calm', 3],
    ],
    '沈んだ希望',
    [
      ['guard', 10],
      ['cost', 0, 2],
      ['trust', -2],
    ],
    ['quiet'],
    '積み重なった氷の板の陰に、船の残骸。',
  ),
  w(
    12,
    'rain',
    '雨、蒸気、速度',
    'J.M.W.ターナー',
    1844,
    'painting',
    ['tech', 'time', 'body'],
    ['AGI'],
    3,
    'common',
    [
      ['hit', S(3, 'AGI')],
      ['guard', 3],
    ],
    '霧の中の兎',
    [['cost', 1], ['leave']],
    ['newPlace'],
    '鉄橋を渡る機関車の前を、兎が走る。',
    { passive: [{ rule: 'leaveChance', fn: (_c, v) => v + 10, text: '去る +10%' }] },
  ),
  w(
    13,
    'cafe',
    '夜のカフェ',
    'フィンセント・ファン・ゴッホ',
    1888,
    'painting',
    ['place', 'night', 'person'],
    ['WIL'],
    3,
    'common',
    [
      ['if', ['night'], [['trust', 2]], [['trust', 1]]],
      ['cost', 0, 1],
    ],
    '赤と緑の衝突',
    [
      ['break', S(5, 'WIL')],
      ['cost', 0, 3],
      ['host', 2],
    ],
    ['trusted'],
    '身を持ち崩すこともできる場所、とその人は書いた。',
    { alter: { overuse: { to: 'vertigo', need: 2 } } },
  ),
  w(
    14,
    'night',
    '夜',
    'フェリックス・ヴァロットン',
    1897,
    'painting',
    ['night', 'private', 'body'],
    ['INT', 'AGI'],
    3,
    'uncommon',
    [
      ['if', ['night'], [['clue', 1]], [['see']]],
      ['host', 1],
    ],
    '黒い版',
    [['clue', 2, true]],
    ['uncover'],
    '黒い面のなかに、白い線だけで人がいる。',
  ),
  w(
    15,
    'prisons',
    '牢獄',
    'ジョヴァンニ・バッティスタ・ピラネージ',
    1750,
    'painting',
    ['place', 'institution', 'time'],
    ['INT'],
    2,
    'uncommon',
    [['stun'], ['host', 2]],
    '終わらない階段',
    [['stun'], ['cost', 0, 2]],
    ['broken'],
    '階段はどこへも着かない。',
  ),
  w(
    16,
    'chirico',
    '通りの神秘と憂愁',
    'ジョルジョ・デ・キリコ',
    1914,
    'painting',
    ['place', 'time', 'memory'],
    ['INT', 'WIL'],
    3,
    'common',
    [['see'], ['calm', 3], ['if', ['foeTag', 'memory'], [['clue', 1]]]],
    '長い影',
    [
      ['clue', 1, true],
      ['cost', 0, 1],
    ],
    ['newPlace'],
    '輪を回す少女の先に、誰かの影。',
    { alter: { care: { to: 'empire', need: 2 } } },
  ),
  w(
    17,
    'empire',
    '光の帝国',
    'ルネ・マグリット',
    1954,
    'painting',
    ['night', 'time', 'gaze'],
    ['INT'],
    3,
    'uncommon',
    [['see'], ['lie', 3, 0, 'harmless']],
    '昼の空',
    [['lie', 4, 10, 'harmless']],
    ['lieKept'],
    '夜の街の上に、昼の空。',
    {
      shift: { on: 'spent', every: 1, cap: 4, perm: 'liar' },
      passive: [{ rule: 'lieChance', when: night, fn: (_c, v) => v + 5, text: '深夜、嘘 +5%' }],
    },
  ),
  w(
    18,
    'karljohan',
    'カール・ヨハン通りの夕べ',
    'エドヴァルド・ムンク',
    1892,
    'painting',
    ['person', 'public', 'gaze'],
    ['WIL'],
    3,
    'common',
    [
      ['break', S(3, 'WIL')],
      ['cost', 0, 1],
    ],
    '群衆の顔',
    [
      ['break', S(6, 'WIL')],
      ['cost', 0, 3],
    ],
    ['broken'],
    '向かってくる顔が、みな同じに青白い。',
    { alter: { overuse: { to: 'pope', need: 2 } } },
  ),
  w(
    19,
    'vertigo',
    '眩暈',
    'レオン・スピリアールト',
    1908,
    'painting',
    ['place', 'body', 'time'],
    ['WIL'],
    2,
    'uncommon',
    [['stun'], ['cost', 0, 2]],
    '落ちる階段',
    [['stun'], ['break', 4], ['cost', 0, 3], ['perm', 'fear', true]],
    ['quiet'],
    '階段だけが、どこまでも下へ。',
  ),
  w(
    20,
    'glove',
    '手袋をめぐる幻想',
    'マックス・クリンガー',
    1881,
    'painting',
    ['private', 'memory', 'body'],
    ['INT', 'WIL'],
    3,
    'uncommon',
    [['clue', 2, true]],
    '奪われた手袋',
    [
      ['clue', 2, true],
      ['cost', 0, 2],
    ],
    ['uncover'],
    '拾った手袋が、夢のなかで大きくなっていく。',
  ),
  w(
    21,
    'pope',
    '教皇インノケンティウス10世の肖像による習作',
    'フランシス・ベーコン',
    1953,
    'painting',
    ['institution', 'body', 'gaze'],
    ['WIL', 'ATK'],
    2,
    'rare',
    [
      ['break', { n: 6, s: 'WIL' }],
      ['break', S(0, 'ATK', 0.5)],
      ['host', 3],
    ],
    '叫び',
    [
      ['break', S(9, 'WIL')],
      ['cost', 0, 3],
      ['host', 10],
    ],
    ['broken'],
    '玉座の上で、口だけが開いている。',
    { passive: [{ rule: 'break', fn: (_c, v) => Math.round(v * 1.1), text: '意志を削る量 ×1.1' }] },
  ),
  w(
    22,
    'nighthawks',
    'ナイトホークス',
    'エドワード・ホッパー',
    1942,
    'painting',
    ['night', 'place', 'gaze', 'person'],
    ['WIL', 'INT'],
    3,
    'rare',
    [['see'], ['trust', 1], ['calm', 3]],
    '誰もいないカウンター',
    [
      ['if', ['night'], [['trust', 2]], [['trust', 1]]],
      ['cost', 0, 2],
    ],
    ['quiet'],
    '閉店しない店の、ガラスの内側。',
    {
      alter: { care: { to: 'interior', need: 2 }, overuse: { to: 'night', need: 2 } },
      hidden: {
        id: 'nighthawks-2am',
        when: ['hour', 4],
        fx: [['trust', 2]],
        text: '2 時を過ぎていれば、信頼 +2',
      },
      passive: [
        { rule: 'turnCalm', when: night, fn: (_c, v) => v + 1, text: '深夜、毎手番 心の構え +1' },
      ],
    },
  ),
  w(
    23,
    'interior',
    '室内',
    'ヴィルヘルム・ハンマースホイ',
    1899,
    'painting',
    ['place', 'private', 'time'],
    ['WIL'],
    4,
    'uncommon',
    [
      ['calm', S(5, 'WIL')],
      ['heal', 0, 2],
    ],
    '背を向けた女',
    [
      ['calm', 6],
      ['trust', -1],
    ],
    ['quiet'],
    '扉の向こうにも、また扉。',
  ),
  w(
    24,
    'khnopff',
    '私は私自身に扉を閉ざす',
    'フェルナン・クノップフ',
    1891,
    'painting',
    ['private', 'memory', 'body'],
    ['WIL', 'DEF'],
    3,
    'uncommon',
    [
      ['calm', S(8, 'WIL')],
      ['guard', 3],
      ['trust', -1],
    ],
    '閉じた扉',
    [
      ['calm', 10],
      ['guard', 4],
      ['trust', -2],
      ['perm', 'closed-heart', true],
    ],
    ['quiet'],
    '鍵は内側にある。',
  ),
  w(
    25,
    'bureau',
    '政府局',
    'ジョージ・トゥーカー',
    1956,
    'painting',
    ['institution', 'public', 'gaze'],
    ['INT'],
    3,
    'uncommon',
    [['stun'], ['host', 1]],
    '番号札',
    [['stun'], ['break', 3], ['cost', 0, 1]],
    ['broken'],
    '窓口の向こうの顔は、どれも同じ。',
  ),
  // ─── 文学・SF ──────────────────────────────────────────────
  w(
    26,
    'lot49',
    '競売ナンバー49の叫び',
    'トマス・ピンチョン',
    1966,
    'book',
    ['private', 'public', 'institution'],
    ['INT'],
    3,
    'common',
    [
      ['clue', 1],
      ['check', 'INT', 30, [['clue', 1]], [['clue', 1, true]]],
    ],
    '弱音器つきの喇叭',
    [
      ['clue', 2, true],
      ['cost', 0, 1],
    ],
    ['uncover'],
    '郵便ラッパの記号が、街じゅうに書いてある。',
    {
      alter: { overuse: { to: 'cosmos', need: 2 } },
      passive: [{ rule: 'falseChance', fn: (_c, v) => v + 10, text: '誤った手がかり +10%' }],
    },
  ),
  w(
    27,
    'correction',
    '推敲',
    'トーマス・ベルンハルト',
    1975,
    'book',
    ['private', 'memory', 'time'],
    ['INT', 'WIL'],
    3,
    'common',
    [
      ['cut', 4],
      ['break', 2],
    ],
    '円錐',
    [
      ['cut', 6],
      ['cost', 0, 2],
    ],
    ['quiet'],
    '一行を直すと、全部を直さなければならなくなる。',
  ),
  w(
    28,
    'boris',
    'ボリス・ダヴィドヴィチのための墓',
    'ダニロ・キシュ',
    1976,
    'book',
    ['institution', 'memory', 'public'],
    ['INT'],
    2,
    'uncommon',
    [
      ['lie', 3, 0, 'authority'],
      ['break', 3],
    ],
    '偽の自白',
    [
      ['break', S(5, 'INT')],
      ['host', 2],
      ['perm', 'liar', true],
    ],
    ['lieKept'],
    '書き換えられた生涯にも、墓は要る。',
  ),
  w(
    29,
    'saturn',
    '土星の環',
    'W.G.ゼーバルト',
    1995,
    'book',
    ['place', 'memory', 'time'],
    ['INT', 'WIL'],
    3,
    'rare',
    [
      ['clue', 1],
      ['heal', 0, 2],
      ['refill', 'memory', 1],
    ],
    'ニシンの群れ',
    [
      ['clue', 1],
      ['cost', 2],
    ],
    ['newPlace'],
    '歩くほどに、話がそれていく。それていった先に、いつも死者がいる。',
    {
      shift: { on: 'rested', every: 2, cap: 4 },
      hidden: {
        id: 'saturn-digression',
        when: ['tag', 'memory', 4],
        fx: [['clue', 1]],
        text: '［記憶］を 4 以上持っていれば、手がかりをもう 1 つ',
      },
    },
  ),
  w(
    30,
    'falling',
    '墜ちていく男',
    'ドン・デリーロ',
    2007,
    'book',
    ['body', 'public', 'memory'],
    ['WIL'],
    3,
    'common',
    [
      ['break', S(4, 'WIL')],
      ['calm', 2],
    ],
    '落ちる姿勢',
    [
      ['break', S(6, 'WIL')],
      ['cost', 0, 3],
    ],
    ['broken'],
    '灰をかぶったまま、街を歩いて帰る。',
  ),
  w(
    31,
    'cosmos',
    'コスモス',
    'ヴィトルド・ゴンブローヴィチ',
    1965,
    'book',
    ['gaze', 'private', 'memory'],
    ['INT'],
    3,
    'uncommon',
    [['clue', 2, true]],
    '吊るされた雀',
    [
      ['clue', 2, true],
      ['break', 2],
      ['cost', 0, 2],
    ],
    ['uncover'],
    '偶然を三つ並べると、意味になってしまう。',
  ),
  w(
    32,
    'voice',
    '天の声',
    'スタニスワフ・レム',
    1968,
    'book',
    ['tech', 'public', 'memory'],
    ['INT'],
    3,
    'uncommon',
    [['check', 'INT', 20, [['clue', 2]], [['see']]]],
    'ニュートリノの手紙',
    [
      ['clue', 1],
      ['cost', 0, 2],
    ],
    ['uncover'],
    '宇宙からの信号を、誰も読み切れない。',
    {
      passive: [
        {
          rule: 'checkChance',
          when: (c) => !!c.stat?.includes('INT'),
          fn: (_c, v) => v + 5,
          text: 'INT 判定 +5%',
        },
      ],
    },
  ),
  w(
    33,
    'w',
    'Wあるいは子供の頃の記憶',
    'ジョルジュ・ペレック',
    1975,
    'book',
    ['memory', 'institution', 'body'],
    ['WIL', 'INT'],
    2,
    'common',
    [['heal', 0, P(2, 'memory')]],
    '空白の章',
    [
      ['heal', 0, 3],
      ['cost', 2],
    ],
    ['newPlace'],
    '思い出せないことを、思い出せないまま書く。',
  ),
  w(
    34,
    'merulana',
    'メルラーナ街のあのひどい混乱',
    'カルロ・エミリオ・ガッダ',
    1957,
    'book',
    ['place', 'person', 'public'],
    ['INT'],
    3,
    'common',
    [
      ['clue', 1],
      ['host', 1],
    ],
    '混乱',
    [
      ['clue', 2, true],
      ['host', 2],
    ],
    ['uncover'],
    '事件はひとつ。言い分は路地の数だけ。',
  ),
  w(
    35,
    'distant',
    '遠い星',
    'ロベルト・ボラーニョ',
    1996,
    'book',
    ['public', 'body', 'night'],
    ['ATK', 'WIL'],
    2,
    'uncommon',
    [
      ['break', S(4, 'WIL')],
      ['hit', 3],
    ],
    '空に書かれた詩',
    [
      ['break', 7],
      ['host', 3],
      ['cost', 0, 2],
    ],
    ['broken'],
    '飛行機雲で書かれた詩は、すぐに消える。',
    {
      passive: [
        { rule: 'break', when: night, fn: (_c, v) => v + 1, text: '深夜、意志を削る量 +1' },
      ],
    },
  ),
  w(
    36,
    'molloy',
    'モロイ',
    'サミュエル・ベケット',
    1951,
    'book',
    ['body', 'place', 'time'],
    ['VIT', 'WIL'],
    3,
    'common',
    [
      ['guard', 4],
      ['heal', 3],
    ],
    '十六個の石',
    [
      ['heal', 5],
      ['cost', 0, 2],
    ],
    ['newPlace'],
    'ポケットの石を、順番に口に入れていく。',
    { alter: { overuse: { to: 'labyrinth', need: 2 } } },
  ),
  w(
    37,
    'ficciones',
    '伝奇集',
    'ホルヘ・ルイス・ボルヘス',
    1944,
    'book',
    ['memory', 'place', 'public'],
    ['INT'],
    3,
    'uncommon',
    [['see'], ['clue', 1]],
    'バベルの図書館',
    [
      ['clue', 3, true],
      ['cost', 0, 2],
    ],
    ['uncover'],
    'すべての本がある図書館で、目当ての一冊だけが見つからない。',
    { passive: [{ rule: 'falseChance', fn: (_c, v) => v - 5, text: '誤った手がかり −5%' }] },
  ),
  w(
    38,
    'crocodiles',
    '鰐の街',
    'ブルーノ・シュルツ',
    1934,
    'book',
    ['place', 'memory', 'private'],
    ['WIL'],
    3,
    'common',
    [
      ['break', 3],
      ['trust', 1],
    ],
    '仕立て屋の人形',
    [
      ['clue', 1, true],
      ['heal', 0, 2],
    ],
    ['newPlace'],
    '父は鳥を飼い、街の地図には描かれない通りがある。',
  ),
  w(
    39,
    'morel',
    'モレルの発明',
    'アドルフォ・ビオイ＝カサーレス',
    1940,
    'book',
    ['tech', 'memory', 'gaze'],
    ['INT'],
    3,
    'uncommon',
    [['see'], ['cut', 5]],
    '永遠の一週間',
    [
      ['cut', 8],
      ['cost', 2],
    ],
    ['quiet'],
    '島の客たちは、同じ一週間を何度も繰り返す。',
    { alter: { overuse: { to: 'mulholland', need: 2 } } },
  ),
  w(
    40,
    'policeman',
    '第三の警官',
    'フラン・オブライエン',
    1967,
    'book',
    ['institution', 'body', 'time'],
    ['INT'],
    2,
    'uncommon',
    [['check', 'INT', 30, [['stun'], ['host', -2]], [['host', 1]]]],
    '自転車の原子',
    [['stun'], ['cost', 2]],
    ['broken'],
    '署の警官は、半分自転車になっている。',
  ),
  w(
    41,
    'labyrinth',
    '迷路のなかで',
    'アラン・ロブ＝グリエ',
    1959,
    'book',
    ['place', 'time', 'body'],
    ['AGI'],
    2,
    'uncommon',
    [['guard', 3], ['see']],
    '雪の街角',
    [['cost', 0, 2], ['leave']],
    ['newPlace'],
    '同じ角、同じ街灯、同じ箱。',
    { restOnly: true },
  ),
  w(
    42,
    'paramo',
    'ペドロ・パラモ',
    'フアン・ルルフォ',
    1955,
    'book',
    ['memory', 'place', 'person'],
    ['WIL'],
    3,
    'common',
    [
      ['break', S(3, 'WIL')],
      ['if', ['foeTag', 'memory'], [['clue', 1]]],
    ],
    '囁き',
    [
      ['clue', 1],
      ['cost', 0, 3],
    ],
    ['newPlace'],
    '村には誰もいないのに、話し声がやまない。',
  ),
  w(
    43,
    'map',
    '燃えつきた地図',
    '安部公房',
    1967,
    'book',
    ['place', 'private', 'memory'],
    ['INT', 'AGI'],
    3,
    'common',
    [
      ['clue', 1],
      ['coins', 4],
    ],
    '消えた男',
    [
      ['clue', 1],
      ['perm', 'past-bound', true],
    ],
    ['uncover'],
    '失踪した男を追ううちに、追う者のほうが消えていく。',
    { alter: { overuse: { to: 'dunes', need: 2 } } },
  ),
  w(
    44,
    'cities',
    '見えない都市',
    'イタロ・カルヴィーノ',
    1972,
    'book',
    ['place', 'memory', 'public'],
    ['INT', 'WIL'],
    3,
    'rare',
    [['see'], ['trust', 2]],
    '旅人の作り話',
    [['lie', 4, 0, 'knows']],
    ['trusted'],
    '語られるどの都市も、ひとつの都市のことかもしれない。',
    {
      alter: { overuse: { to: 'ficciones', need: 2 } },
      passive: [{ rule: 'storyChance', fn: (_c, v) => v + 5, text: '出来事の判定 +5%' }],
    },
  ),
  w(
    45,
    'ice',
    '氷',
    'アンナ・カヴァン',
    1967,
    'book',
    ['body', 'time', 'private'],
    ['WIL'],
    3,
    'common',
    [
      ['hit', 4],
      ['cut', 3],
    ],
    '迫る氷',
    [
      ['hit', 6],
      ['cost', 0, 2],
    ],
    ['win'],
    '氷の壁が、少しずつ世界を狭めてくる。',
  ),
  w(
    46,
    'ubik',
    'ユービック',
    'フィリップ・K・ディック',
    1969,
    'book',
    ['tech', 'time', 'memory'],
    ['INT', 'WIL'],
    2,
    'uncommon',
    [['heal', 2, 4]],
    '退行',
    [
      ['heal', 0, 3],
      ['cost', 1],
    ],
    ['newPlace'],
    '硬貨が古くなり、牛乳が腐る。時間が後ろへ流れている。',
    {
      hidden: {
        id: 'ubik-spray',
        when: ['lowMind'],
        fx: [['heal', 0, 99]],
        text: '精神が 1/3 を切っていれば、精神を満たす',
      },
      passive: [
        {
          rule: 'selfCost',
          when: (c) => c.kind === 'mind',
          fn: (_c, v) => Math.max(0, v - 1),
          text: '精神の代償 −1',
        },
      ],
    },
  ),
  w(
    47,
    'android',
    'アンドロイドは電気羊の夢を見るか？',
    'フィリップ・K・ディック',
    1968,
    'book',
    ['person', 'gaze', 'tech'],
    ['INT', 'WIL'],
    3,
    'common',
    [['see'], ['if', ['lying'], [['break', 6]], [['trust', 1]]]],
    '共感の検査',
    [['see'], ['break', 4], ['host', 2]],
    ['uncover'],
    '共感できるかどうかで、人間かどうかを決める。',
    {
      alter: { care: { to: 'bladerunner', need: 2 } },
      hidden: {
        id: 'android-test',
        when: ['lying'],
        fx: [['clue', 1]],
        text: '相手が嘘をついていれば、手がかりを 1 つ',
      },
    },
  ),
  w(
    48,
    'orwell',
    '1984年',
    'ジョージ・オーウェル',
    1949,
    'book',
    ['institution', 'gaze', 'public'],
    ['INT', 'WIL'],
    2,
    'rare',
    [['see'], ['break', S(4, 'INT')]],
    '二分間憎悪',
    [
      ['break', 7],
      ['host', 3],
      ['trust', -2],
    ],
    ['broken'],
    '見られていることを、見せられる。',
    {
      alter: { overuse: { to: 'bureau', need: 2 } },
      passive: [
        {
          rule: 'intentVisible',
          when: foeHas('institution'),
          fn: () => 1,
          text: '［制度］の相手の予告は嘘でも見える',
        },
      ],
    },
  ),
  w(
    49,
    'miserables',
    'レ・ミゼラブル',
    'ヴィクトル・ユゴー',
    1862,
    'book',
    ['trust', 'institution', 'body'],
    ['WIL', 'VIT'],
    3,
    'rare',
    [
      ['trust', 3],
      ['coins', -5],
    ],
    '銀の燭台',
    [
      ['trust', 4],
      ['coins', -10],
      ['host', -2],
    ],
    ['trusted'],
    '盗まれた燭台を、もう一本差し出す。',
    {
      hidden: {
        id: 'miserables-mercy',
        when: ['hostile', 7],
        fx: [['trust', 3]],
        text: '敵意が 7 以上なら、信頼をさらに +3',
      },
    },
  ),
  w(
    50,
    'threebody',
    '三体',
    '劉慈欣',
    2008,
    'book',
    ['tech', 'public', 'private'],
    ['INT'],
    2,
    'uncommon',
    [['see'], ['expose', 2]],
    '暗い森',
    [
      ['break', S(8, 'INT')],
      ['host', 10],
      ['cost', 0, 2],
    ],
    ['broken'],
    '居場所を知られた者から、消される。',
  ),
  w(
    51,
    'chrome',
    'クローム襲撃',
    'ウィリアム・ギブスン',
    1982,
    'book',
    ['tech', 'private', 'institution'],
    ['INT', 'AGI'],
    2,
    'rare',
    [
      ['clue', 1],
      ['coins', 8],
      ['expose', 2],
    ],
    '黒い氷',
    [
      ['clue', 2],
      ['coins', 12],
      ['cost', 0, 3],
    ],
    ['uncover'],
    '氷を割って、誰かの金庫に入る。',
  ),
  w(
    52,
    'solaris',
    'ソラリス',
    'スタニスワフ・レム',
    1961,
    'book',
    ['memory', 'person', 'gaze'],
    ['WIL', 'INT'],
    3,
    'uncommon',
    [
      ['heal', 0, 2],
      ['if', ['foeTag', 'memory'], [['clue', 1]], [['see']]],
    ],
    '訪問者',
    [
      ['break', S(5, 'WIL')],
      ['cost', 0, 3],
    ],
    ['quiet'],
    '海は、あなたが一番思い出したくない人を連れてくる。',
    {
      alter: { secret: { to: 'stalker', perms: ['accident'] } },
      hidden: {
        id: 'solaris-guest',
        when: ['tag', 'memory', 3],
        fx: [['clue', 1]],
        text: '［記憶］を 3 以上持っていれば、手がかりを 1 つ',
      },
    },
  ),
  w(
    53,
    'picnic',
    '路傍のピクニック',
    'アルカジイ＆ボリス・ストルガツキー',
    1972,
    'book',
    ['place', 'tech', 'public'],
    ['AGI', 'INT'],
    3,
    'common',
    [
      ['coins', 6],
      ['clue', 1],
    ],
    '黄金の球',
    [
      ['coins', 15],
      ['cost', 4],
    ],
    ['newPlace'],
    '異星人が立ち寄ったあとの空き地に、使い道のわからない品々。',
    { alter: { overuse: { to: 'stalker', need: 2 } } },
  ),
  w(
    54,
    'dune',
    'デューン 砂の惑星',
    'フランク・ハーバート',
    1965,
    'book',
    ['place', 'time', 'institution'],
    ['WIL', 'INT'],
    3,
    'uncommon',
    [['see'], ['calm', 3]],
    'スパイス',
    [['see'], ['clue', 1], ['cost', 3]],
    ['quiet'],
    '恐れは、心を殺すもの。',
    {
      hidden: {
        id: 'dune-litany',
        when: ['lowMind'],
        fx: [['calm', 10]],
        text: '精神が 1/3 を切っていれば、心の構え 10',
      },
      passive: [{ rule: 'threatTaken', fn: (_c, v) => Math.max(0, v - 1), text: '精神への傷 −1' }],
    },
  ),
  w(
    55,
    'leaves',
    '紙葉の家',
    'マーク・Z・ダニエレブスキー',
    2000,
    'book',
    ['place', 'private', 'memory'],
    ['INT'],
    3,
    'rare',
    [
      ['clue', 1],
      ['guard', 3],
    ],
    '五分半の廊下',
    [
      ['clue', 2],
      ['cost', 0, 3],
    ],
    ['uncover'],
    '家の内側の寸法が、外側より少し大きい。',
  ),
  // ─── 映画 ──────────────────────────────────────────────────
  w(
    56,
    'ironman',
    'アイアンマン',
    'ジョン・ファヴロー',
    2008,
    'film',
    ['tech', 'body', 'public'],
    ['ATK', 'DEF'],
    3,
    'rare',
    [
      ['guard', S(5, 'DEF')],
      ['hit', S(3, 'ATK')],
    ],
    '試作のスーツ',
    [
      ['hit', S(6, 'ATK')],
      ['guard', 6],
      ['cost', 2],
    ],
    ['win'],
    '洞窟で、廃材から鎧を組み上げる。',
    {
      passive: [
        {
          rule: 'guardKeep',
          fn: (_c, v) => Math.max(v, 0.5),
          text: '守りが手番をまたいで半分残る',
        },
      ],
    },
  ),
  w(
    57,
    'darkknight',
    'ダークナイト',
    'クリストファー・ノーラン',
    2008,
    'film',
    ['night', 'institution', 'body'],
    ['ATK', 'WIL'],
    3,
    'uncommon',
    [
      ['hit', S(4, 'ATK')],
      ['break', 3],
    ],
    '選ばれた悪役',
    [
      ['break', { n: 6, s: 'WIL' }],
      ['hit', S(0, 'ATK')],
      ['cost', 2],
      ['trust', -3],
    ],
    ['win'],
    '街に必要なのは、英雄か、それとも。',
    {
      alter: { overuse: { to: 'seven', need: 2 } },
      passive: [{ rule: 'hit', when: night, fn: (_c, v) => v + 1, text: '深夜、体力を削る量 +1' }],
    },
  ),
  w(
    58,
    'pulp',
    'パルプ・フィクション',
    'クエンティン・タランティーノ',
    1994,
    'film',
    ['person', 'time', 'body'],
    ['AGI', 'ATK'],
    3,
    'common',
    [
      ['hit', S(4, 'AGI')],
      ['check', 'AGI', 30, [['stun']]],
    ],
    'ブリーフケース',
    [
      ['coins', 10],
      ['clue', 1, true],
      ['host', 2],
    ],
    ['win'],
    '話の順番を入れ替えると、死んだ男が戻ってくる。',
  ),
  w(
    59,
    'rim',
    'パシフィック・リム',
    'ギレルモ・デル・トロ',
    2013,
    'film',
    ['tech', 'body', 'person'],
    ['ATK', 'VIT'],
    3,
    'common',
    [
      ['hit', S(6, 'ATK')],
      ['guard', 3],
    ],
    'ドリフト',
    [
      ['hit', S(8, 'ATK')],
      ['cost', 0, 3],
    ],
    ['win'],
    '二人で一つの体を動かす。記憶ごと。',
    {
      alter: { overuse: { to: 'akira', need: 2 } },
      hidden: {
        id: 'rim-drift',
        when: ['tag', 'body', 3],
        fx: [['guard', 6]],
        text: '［身体］を 3 以上持っていれば、守り +6',
      },
    },
  ),
  w(
    60,
    'jaws',
    'ジョーズ',
    'スティーヴン・スピルバーグ',
    1975,
    'film',
    ['body', 'place', 'public'],
    ['WIL', 'ATK'],
    3,
    'common',
    [
      ['break', S(5, 'WIL')],
      ['host', 2],
    ],
    'もっと大きな船',
    [
      ['break', 8],
      ['cost', 2],
    ],
    ['broken'],
    '海開きの日、浜の掲示は書き換えられない。',
  ),
  w(
    61,
    't2',
    'ターミネーター2',
    'ジェームズ・キャメロン',
    1991,
    'film',
    ['tech', 'body', 'time'],
    ['VIT', 'DEF'],
    3,
    'common',
    [
      ['guard', S(6, 'DEF')],
      ['heal', 2],
    ],
    '溶鉱炉',
    [
      ['hit', S(7, 'ATK')],
      ['guard', 5],
    ],
    ['win'],
    '守るために、未来から送られてきた。',
    { passive: [{ rule: 'turnGuard', fn: (_c, v) => v + 1, text: '毎手番 守り +1' }] },
  ),
  w(
    62,
    'robocop',
    'ロボコップ',
    'ポール・ヴァーホーヴェン',
    1987,
    'film',
    ['institution', 'tech', 'body'],
    ['DEF', 'ATK'],
    3,
    'common',
    [['hit', S(4, 'ATK')], ['guard', 4], ['see']],
    '第四指令',
    [
      ['hit', 8],
      ['cost', 4],
    ],
    ['win'],
    '会社の重役には、手が出せないように作られている。',
  ),
  w(
    63,
    'alien',
    'エイリアン',
    'リドリー・スコット',
    1979,
    'film',
    ['body', 'tech', 'night'],
    ['AGI', 'VIT'],
    3,
    'common',
    [
      ['guard', 3],
      ['hit', 4],
    ],
    '胸を破るもの',
    [
      ['hit', 9],
      ['cost', 5],
    ],
    ['win'],
    '宇宙では、叫んでも誰にも聞こえない。',
    {
      hidden: {
        id: 'alien-ripley',
        when: ['lowHp'],
        fx: [['hit', 8]],
        text: '体力が 1/3 を切っていれば、体力をさらに 8 削る',
      },
    },
  ),
  w(
    64,
    'bladerunner',
    'ブレードランナー',
    'リドリー・スコット',
    1982,
    'film',
    ['gaze', 'person', 'night', 'tech'],
    ['INT', 'WIL'],
    3,
    'uncommon',
    [['see'], ['clue', 1], ['if', ['lying'], [['break', S(4, 'WIL')]]]],
    '雨の中の涙',
    [
      ['heal', 0, 4],
      ['trust', 2],
      ['cost', 2],
    ],
    ['uncover'],
    '酸性雨の夜、記憶を植えられた者たちを追う。',
    {
      alter: { secret: { to: 'ghost', perms: ['projected'] } },
      hidden: {
        id: 'bladerunner-tears',
        when: ['lowHp'],
        fx: [['heal', 0, 6]],
        text: '体力が 1/3 を切っていれば、精神 +6',
      },
    },
  ),
  w(
    65,
    'thing',
    '遊星からの物体X',
    'ジョン・カーペンター',
    1982,
    'film',
    ['body', 'trust', 'night'],
    ['INT'],
    2,
    'uncommon',
    [['see'], ['break', 3], ['trust', -1]],
    '血液検査',
    [['see'], ['clue', 1], ['cost', 3]],
    ['uncover'],
    '誰が本物か、熱した針を血に当てるまでわからない。',
  ),
  w(
    66,
    'matrix',
    'マトリックス',
    'ウォシャウスキー姉妹',
    1999,
    'film',
    ['tech', 'gaze', 'public'],
    ['AGI', 'INT'],
    3,
    'rare',
    [['see'], ['guard', 4]],
    '赤い薬',
    [['see'], ['clue', 2], ['cost', 0, 3], ['perm', 'belief', true]],
    ['uncover'],
    '弾丸が、ゆっくりに見える。',
    { passive: [{ rule: 'leaveChance', fn: (_c, v) => v + 10, text: '去る +10%' }] },
  ),
  w(
    67,
    'fightclub',
    'ファイト・クラブ',
    'デヴィッド・フィンチャー',
    1999,
    'film',
    ['body', 'private', 'person'],
    ['ATK', 'VIT'],
    3,
    'common',
    [
      ['hit', S(5, 'ATK')],
      ['cost', 2],
    ],
    '自分を殴る',
    [
      ['cost', 4],
      ['break', 7],
      ['perm', 'blood', true],
    ],
    ['win'],
    '最初のルールは、話さないこと。',
  ),
  w(
    68,
    'seven',
    'セブン',
    'デヴィッド・フィンチャー',
    1995,
    'film',
    ['institution', 'gaze', 'private'],
    ['INT'],
    3,
    'common',
    [
      ['clue', 1],
      ['break', 2],
    ],
    '箱の中身',
    [
      ['clue', 2],
      ['cost', 0, 4],
    ],
    ['uncover'],
    '雨の七日間、七つの罪。',
  ),
  w(
    69,
    'heat',
    'ヒート',
    'マイケル・マン',
    1995,
    'film',
    ['time', 'body', 'institution'],
    ['AGI', 'ATK'],
    3,
    'rare',
    [['hit', S(5, 'AGI')]],
    '三十秒',
    [['coins', 10], ['leave']],
    ['win'],
    '踏み込まれたら、三十秒で全部を置いて出ていく。',
    { passive: [{ rule: 'leaveChance', fn: (_c, v) => v + 15, text: '去る +15%' }] },
  ),
  w(
    70,
    'children',
    'トゥモロー・ワールド',
    'アルフォンソ・キュアロン',
    2006,
    'film',
    ['trust', 'body', 'public'],
    ['WIL', 'VIT'],
    3,
    'common',
    [
      ['trust', 2],
      ['guard', 3],
    ],
    '最後の子供',
    [
      ['trust', 3],
      ['cost', 4],
    ],
    ['trusted'],
    '銃声が、赤ん坊の泣き声で止まる。',
  ),
  w(
    71,
    'odyssey',
    '2001年宇宙の旅',
    'スタンリー・キューブリック',
    1968,
    'film',
    ['tech', 'time', 'gaze'],
    ['INT'],
    2,
    'uncommon',
    [['stun'], ['see']],
    '赤い目',
    [['stun'], ['cost', 0, 2]],
    ['quiet'],
    '骨が空に投げ上げられて、宇宙船になる。',
    {
      hidden: {
        id: 'odyssey-child',
        when: ['hour', 6],
        fx: [['break', 8]],
        text: '4 時を過ぎていれば、意志を 8 削る',
      },
    },
  ),
  w(
    72,
    'brazil',
    '未来世紀ブラジル',
    'テリー・ギリアム',
    1985,
    'film',
    ['institution', 'public', 'private'],
    ['INT', 'WIL'],
    3,
    'common',
    [
      ['cut', 4],
      ['heal', 0, 2],
    ],
    '書類 27B/6',
    [['stun'], ['cost', 0, 2]],
    ['quiet'],
    '一匹の虫が、タイプライターの字を一文字変える。',
    { passive: [{ rule: 'price', fn: (_c, v) => Math.round(v * 0.9), text: '値段 ×0.9' }] },
  ),
  w(
    73,
    'conversation',
    'カンバセーション…盗聴…',
    'フランシス・フォード・コッポラ',
    1974,
    'film',
    ['private', 'tech', 'gaze'],
    ['INT'],
    3,
    'common',
    [['clue', 1], ['see']],
    '壁の中の盗聴器',
    [
      ['clue', 2],
      ['cost', 0, 3],
      ['perm', 'suspicion', true],
    ],
    ['uncover'],
    '録った声は、聞き直すたびに意味が変わる。',
    {
      passive: [
        {
          rule: 'intentVisible',
          when: (c) => (c.enc?.foe.hostility ?? 0) >= 6,
          fn: () => 1,
          text: '敵意 6 以上の相手の予告は嘘でも見える',
        },
      ],
    },
  ),
  w(
    74,
    'mulholland',
    'マルホランド・ドライブ',
    'デヴィッド・リンチ',
    2001,
    'film',
    ['memory', 'night', 'private'],
    ['WIL'],
    3,
    'uncommon',
    [
      ['clue', 2, true],
      ['calm', 2],
    ],
    '青い鍵',
    [
      ['clue', 3, true],
      ['cost', 0, 3],
    ],
    ['quiet'],
    '夢の前半が、現実の後半を書き換える。',
  ),
  w(
    75,
    'stalker',
    'ストーカー',
    'アンドレイ・タルコフスキー',
    1979,
    'film',
    ['place', 'time', 'trust'],
    ['WIL', 'AGI'],
    3,
    'rare',
    [['see'], ['calm', 4]],
    '部屋',
    [
      ['clue', 2],
      ['cost', 3],
    ],
    ['newPlace'],
    'ゾーンでは、まっすぐ歩くのがいちばん遠回りだ。',
    {
      hidden: {
        id: 'stalker-room',
        when: ['shown', 2],
        fx: [['heal', 0, 5]],
        text: '手がかりが 2 つ以上見えていれば、精神 +5',
      },
    },
  ),
  w(
    76,
    'highlow',
    '天国と地獄',
    '黒澤明',
    1963,
    'film',
    ['public', 'private', 'institution'],
    ['INT'],
    3,
    'rare',
    [
      ['coins', -8],
      ['trust', 3],
    ],
    '身代金',
    [
      ['coins', -20],
      ['trust', 5],
      ['clue', 1],
    ],
    ['trusted'],
    '丘の上の家は、下の町からいつも見えている。',
    {
      hidden: {
        id: 'highlow-smoke',
        when: ['lying'],
        fx: [['break', 6]],
        text: '相手が嘘をついていれば、意志を 6 削る',
      },
    },
  ),
  w(
    77,
    'dunes',
    '砂の女',
    '勅使河原宏',
    1964,
    'film',
    ['place', 'body', 'time'],
    ['VIT', 'WIL'],
    3,
    'uncommon',
    [
      ['guard', 4],
      ['heal', 3],
    ],
    '砂を掻く',
    [['stun'], ['cost', 2]],
    ['quiet'],
    '砂を掻き出さないと、家が埋まる。毎晩。',
  ),
  w(
    78,
    'cure',
    'CURE',
    '黒沢清',
    1997,
    'film',
    ['private', 'memory', 'person'],
    ['WIL', 'INT'],
    3,
    'uncommon',
    [
      ['break', S(5, 'WIL')],
      ['host', -1],
    ],
    'X の字',
    [
      ['break', S(8, 'WIL')],
      ['cost', 0, 3],
      ['perm', 'past-bound', true],
    ],
    ['broken'],
    '「あんた、誰だ」と訊かれ続けると、答えがなくなる。',
    {
      hidden: {
        id: 'cure-question',
        when: ['trustHalf'],
        fx: [['stun']],
        text: '信頼が半ばを越えていれば、相手は動けない',
      },
    },
  ),
  w(
    79,
    'akira',
    'AKIRA',
    '大友克洋',
    1988,
    'film',
    ['body', 'tech', 'public'],
    ['ATK', 'WIL'],
    2,
    'uncommon',
    [
      ['hit', S(6, 'ATK')],
      ['cost', 0, 1],
    ],
    '膨張',
    [
      ['hit', S(10, 'ATK')],
      ['cost', 3, 3],
    ],
    ['win'],
    'ネオ東京の地下で、力が膨れ上がる。',
  ),
  w(
    80,
    'ghost',
    'GHOST IN THE SHELL／攻殻機動隊',
    '押井守',
    1995,
    'film',
    ['tech', 'private', 'memory'],
    ['INT', 'AGI'],
    3,
    'uncommon',
    [['clue', 1], ['see']],
    '電脳への潜入',
    [
      ['clue', 2],
      ['break', 3],
      ['cost', 0, 3],
    ],
    ['uncover'],
    '記憶が書き換えられるなら、自分はどこにいる。',
    {
      hidden: {
        id: 'ghost-dive',
        when: ['foeTag', 'tech'],
        fx: [['clue', 1]],
        text: '相手が［技術］なら、手がかりをもう 1 つ',
      },
    },
  ),
  // ─── 思想・社会科学・建築 ──────────────────────────────────
  w(
    81,
    'federalist',
    'ザ・フェデラリスト',
    'ハミルトン／マディソン／ジェイ',
    1788,
    'thought',
    ['institution', 'public', 'trust'],
    ['INT', 'WIL'],
    3,
    'common',
    [
      ['trust', 2],
      ['guard', 2],
    ],
    '第十篇',
    [
      ['trust', 3],
      ['host', -1],
      ['cost', 0, 1],
    ],
    ['trusted'],
    '派閥は消せない。だから、派閥どうしを抑え合わせる。',
    {
      passive: [
        {
          rule: 'trust',
          when: foeHas('institution'),
          fn: (_c, v) => v + 1,
          text: '［制度］の相手に、信頼 +1',
        },
      ],
    },
  ),
  w(
    82,
    'objectivity',
    '社会科学と社会政策にかかわる認識の「客観性」',
    'マックス・ヴェーバー',
    1904,
    'thought',
    ['public', 'institution', 'gaze'],
    ['INT'],
    3,
    'common',
    [['see'], ['cut', 3]],
    '理念型',
    [['see'], ['clue', 1], ['cost', 0, 1]],
    ['uncover'],
    '現実を測るために、現実にはない純粋な型を作る。',
    { alter: { care: { to: 'ethic', need: 2 } } },
  ),
  w(
    83,
    'ethic',
    'プロテスタンティズムの倫理と資本主義の精神',
    'マックス・ヴェーバー',
    1905,
    'thought',
    ['institution', 'time', 'body'],
    ['WIL', 'INT'],
    3,
    'uncommon',
    [
      ['coins', 6],
      ['calm', 3],
    ],
    '鉄の檻',
    [
      ['coins', 12],
      ['cost', 0, 3],
    ],
    ['quiet'],
    '働くことが救いのしるしになり、やがて檻になる。',
    { passive: [{ rule: 'coins', fn: (_c, v) => Math.round(v * 1.15), text: '金の入り ×1.15' }] },
  ),
  w(
    84,
    'democracy',
    'アメリカのデモクラシー',
    'アレクシ・ド・トクヴィル',
    1835,
    'thought',
    ['institution', 'person', 'public'],
    ['INT', 'WIL'],
    3,
    'common',
    [
      ['trust', 2],
      ['host', -1],
    ],
    '多数者の専制',
    [
      ['break', 5],
      ['trust', -1],
    ],
    ['trusted'],
    '平等は、人を孤立させもする。',
  ),
  w(
    85,
    'leviathan',
    'リヴァイアサン',
    'トマス・ホッブズ',
    1651,
    'thought',
    ['institution', 'body', 'public'],
    ['ATK', 'WIL'],
    3,
    'common',
    [
      ['break', S(4, 'ATK')],
      ['guard', 3],
    ],
    '万人の闘争',
    [
      ['hit', S(6, 'ATK')],
      ['break', 4],
      ['host', 3],
    ],
    ['broken'],
    '剣のない約束は、ただの言葉にすぎない。',
    { passive: [{ rule: 'startHostility', fn: (_c, v) => v - 1, text: '遭遇の初めの敵意 −1' }] },
  ),
  w(
    86,
    'origins',
    '全体主義の起源',
    'ハンナ・アーレント',
    1951,
    'thought',
    ['institution', 'memory', 'public'],
    ['INT', 'WIL'],
    2,
    'uncommon',
    [['break', S(5, 'INT')]],
    '孤独',
    [
      ['break', 8],
      ['cost', 0, 3],
    ],
    ['broken'],
    '孤立した人々が、ひとつの運動に溶ける。',
    { alter: { overuse: { to: 'orwell', need: 2 } } },
  ),
  w(
    87,
    'discipline',
    '監獄の誕生',
    'ミシェル・フーコー',
    1975,
    'thought',
    ['institution', 'gaze', 'body'],
    ['INT'],
    3,
    'common',
    [['see'], ['break', 3]],
    '一望監視',
    [['see'], ['break', 6], ['host', 2]],
    ['broken'],
    '見られているかもしれない、だけで人は振る舞いを変える。',
    {
      alter: { overuse: { to: 'prisons', need: 2 } },
      passive: [
        {
          rule: 'intentVisible',
          when: (c) => (c.enc?.turn ?? 9) === 1,
          fn: () => 1,
          text: '最初の手番は、相手の予告が嘘でも見える',
        },
      ],
    },
  ),
  w(
    88,
    'transformation',
    '大転換',
    'カール・ポランニー',
    1944,
    'thought',
    ['public', 'institution', 'time'],
    ['INT'],
    3,
    'common',
    [
      ['coins', 6],
      ['host', -1],
    ],
    '悪魔のひき臼',
    [
      ['coins', 14],
      ['trust', -2],
    ],
    ['quiet'],
    '土地も人も、売り物ではなかった。',
    { passive: [{ rule: 'coins', fn: (_c, v) => Math.round(v * 1.2), text: '金の入り ×1.2' }] },
  ),
  w(
    89,
    'seeing',
    '国家のように見る',
    'ジェームズ・C・スコット',
    1998,
    'thought',
    ['gaze', 'institution', 'place'],
    ['INT'],
    3,
    'common',
    [['see'], ['clue', 1]],
    '単純化',
    [
      ['clue', 1, true],
      ['break', 3],
    ],
    ['uncover'],
    '読みやすい地図のために、森をまっすぐに植え直す。',
    {
      shift: { on: 'rested', every: 3, cap: 5, perm: 'habit-observe' },
      passive: [{ rule: 'falseChance', fn: (_c, v) => v - 10, text: '誤った手がかり −10%' }],
    },
  ),
  w(
    90,
    'presentation',
    '行為と演技',
    'アーヴィング・ゴッフマン',
    1959,
    'thought',
    ['person', 'public', 'private'],
    ['INT', 'WIL'],
    3,
    'common',
    [['lie', 3, 0, 'ally']],
    '舞台裏',
    [
      ['clue', 1],
      ['lie', 3, 10, 'ally'],
    ],
    ['lieKept'],
    '誰もが、表舞台と舞台裏を持っている。',
    {
      alter: { overuse: { to: 'boris', need: 3 } },
      shift: { on: 'spent', every: 1, cap: 5, perm: 'liar' },
      passive: [{ rule: 'lieChance', fn: (_c, v) => v + 10, text: '嘘 +10%' }],
    },
  ),
  w(
    91,
    'metropolis',
    '大都市と精神生活',
    'ゲオルク・ジンメル',
    1903,
    'thought',
    ['place', 'person', 'public'],
    ['WIL'],
    4,
    'common',
    [
      ['calm', 4],
      ['host', -1],
    ],
    '無関心',
    [
      ['calm', 6],
      ['trust', -1],
    ],
    ['quiet'],
    '刺激が多すぎる街では、人は何にも驚かなくなる。',
    {
      passive: [{ rule: 'threatTaken', fn: (_c, v) => Math.max(0, v - 1), text: '精神への傷 −1' }],
    },
  ),
  w(
    92,
    'revolutions',
    '科学革命の構造',
    'トーマス・S・クーン',
    1962,
    'thought',
    ['public', 'tech', 'time'],
    ['INT'],
    3,
    'uncommon',
    [
      ['cut', 3],
      ['if', ['shown', 2], [['clue', 1]]],
    ],
    'パラダイム転換',
    [
      ['break', S(6, 'INT')],
      ['cost', 0, 2],
    ],
    ['uncover'],
    '説明できない例外が溜まると、世界の見え方ごと変わる。',
    { passive: [{ rule: 'checkChance', fn: (_c, v) => v + 3, text: '判定 +3%' }] },
  ),
  w(
    93,
    'cybernetics',
    'サイバネティックス',
    'ノーバート・ウィーナー',
    1948,
    'thought',
    ['tech', 'time', 'gaze'],
    ['INT'],
    3,
    'common',
    [['see'], ['cut', 4]],
    '負帰還',
    [
      ['cut', 6],
      ['cost', 0, 1],
    ],
    ['quiet'],
    '結果を入口に戻すと、機械が目的を持ったように振る舞う。',
  ),
  w(
    94,
    'artificial',
    'システムの科学',
    'ハーバート・A・サイモン',
    1969,
    'thought',
    ['tech', 'public', 'institution'],
    ['INT'],
    2,
    'uncommon',
    [['see'], ['refill', 'tech', 1]],
    '満足化',
    [
      ['refill', 'public', 1],
      ['cost', 0, 1],
    ],
    ['quiet'],
    '最良でなくてよい。十分であれば。',
    { passive: [{ rule: 'heal', fn: (_c, v) => (v > 0 ? v + 1 : v), text: '回復 +1' }] },
  ),
  w(
    95,
    'vernacular',
    '建築家なしの建築',
    'バーナード・ルドフスキー',
    1964,
    'thought',
    ['place', 'body', 'public'],
    ['VIT', 'DEF'],
    3,
    'common',
    [['guard', S(5, 'DEF')]],
    '名もない家',
    [
      ['guard', 7],
      ['cost', 1],
    ],
    ['win'],
    '誰が建てたかわからない家ほど、よく建っている。',
    { passive: [{ rule: 'turnGuard', fn: (_c, v) => v + 1, text: '毎手番 守り +1' }] },
  ),
  w(
    96,
    'jacobs',
    'アメリカ大都市の死と生',
    'ジェイン・ジェイコブズ',
    1961,
    'thought',
    ['place', 'person', 'trust'],
    ['WIL'],
    3,
    'common',
    [['trust', 2], ['see']],
    '街路の目',
    [
      ['trust', 2],
      ['cost', 0, 1],
    ],
    ['trusted'],
    '歩道に目があれば、通りは安全になる。',
    {
      alter: { care: { to: 'federalist', need: 2 } },
      passive: [
        {
          rule: 'startTrust',
          when: foeHas('person'),
          fn: (_c, v) => v + 1,
          text: '［人物］の相手は、初めから信頼 +1',
        },
      ],
    },
  ),
  w(
    97,
    'pattern',
    'パタン・ランゲージ',
    'クリストファー・アレグザンダーほか',
    1977,
    'thought',
    ['place', 'public', 'body'],
    ['INT', 'WIL'],
    3,
    'common',
    [
      ['guard', 3],
      ['calm', 3],
      ['heal', 2],
    ],
    '窓辺の居場所',
    [
      ['heal', 4],
      ['cost', 0, 1],
    ],
    ['quiet'],
    '光が二方向から入る部屋に、人は集まる。',
    { passive: [{ rule: 'restHeal', fn: (_c, v) => v + 5, text: '休むと +5 回復' }] },
  ),
  w(
    98,
    'image',
    '都市のイメージ',
    'ケヴィン・リンチ',
    1960,
    'thought',
    ['place', 'memory', 'gaze'],
    ['INT'],
    3,
    'common',
    [['see'], ['if', ['foeTag', 'place'], [['clue', 1]], [['calm', 2]]]],
    '迷子',
    [['cost', 0, 1], ['leave']],
    ['newPlace'],
    '道・縁・地区・結節点・目印。人は街をこの五つで覚える。',
    {
      alter: { care: { to: 'pattern', need: 2 } },
      passive: [{ rule: 'storyChance', fn: (_c, v) => v + 10, text: '出来事の判定 +10%' }],
    },
  ),
  w(
    99,
    'space',
    '空間の生産',
    'アンリ・ルフェーヴル',
    1974,
    'thought',
    ['place', 'institution', 'public'],
    ['INT', 'WIL'],
    3,
    'common',
    [
      ['break', 3],
      ['trust', 1],
    ],
    '取り戻された空間',
    [
      ['break', 5],
      ['host', 1],
    ],
    ['broken'],
    '空間は、そこにあるのではなく、作られる。',
  ),
  w(
    100,
    'delirious',
    '錯乱のニューヨーク',
    'レム・コールハース',
    1978,
    'thought',
    ['place', 'tech', 'night'],
    ['INT', 'AGI'],
    3,
    'uncommon',
    [
      ['coins', 5],
      ['calm', 3],
    ],
    '摩天楼の一階ずつ',
    [
      ['coins', 10],
      ['cost', 2],
    ],
    ['newPlace'],
    'ひとつのビルの階ごとに、別の世界がある。',
  ),
];
