import type { ItemDef } from './defs';

/** 所持品。カードの種類ごとに回数を戻すものと、体と心を戻すもの。 */
export const ITEM_LIST: readonly ItemDef[] = [
  {
    id: 'notebook',
    name: '手帳',
    text: '調べるカード（観察・掘るの系統）の回数を 2 戻す。',
    refill: { cats: ['look'], n: 2 },
    price: 30,
    flavor: '前の持ち主の字で、角度と距離が書いてある。',
  },
  {
    id: 'cigarette',
    name: '煙草',
    text: '心のカード（沈黙・思い出すの系統）の回数を 2 戻し、精神を 3 戻す。',
    refill: { cats: ['mind'], n: 2 },
    heal: { mind: 3 },
    price: 25,
    flavor: 'PHILLIES。最後の一本。',
  },
  {
    id: 'bandage',
    name: '包帯',
    text: '体力を 10 戻す。',
    heal: { hp: 10 },
    price: 20,
    flavor: '少し、足りない長さ。',
  },
  {
    id: 'whisky',
    name: 'ウイスキー',
    text: '話すカード（嘘・取引）の回数を 2 戻す。',
    refill: { cats: ['talk'], n: 2 },
    price: 30,
    flavor: '口が軽くなる。',
  },
  {
    id: 'brass',
    name: 'メリケンサック',
    text: '力のカード（威圧・殴るの系統）の回数を 2 戻す。',
    refill: { cats: ['force'], n: 2 },
    price: 30,
    flavor: '指に、ちょうど合う。',
  },
  {
    id: 'bus-ticket',
    name: '回数券',
    text: '逃げるカード（逃走・掠め取る）の回数を 1 戻す。',
    refill: { cats: ['flee'], n: 1 },
    price: 30,
    flavor: '終バスは、もう出た。',
  },
  {
    id: 'coffee',
    name: 'コーヒー',
    text: '精神を 8 戻す。',
    heal: { mind: 8 },
    price: 18,
    flavor: '深夜の食堂の、煮詰まった一杯。',
  },
  {
    id: 'photo',
    name: '古い写真',
    text: 'すべてのカードの回数を 1 戻す。',
    refill: { cats: ['look', 'force', 'mind', 'talk', 'flee', 'body'], n: 1 },
    price: 55,
    flavor: '裏に、日付だけ。',
  },
];
